const instrument_map = [
  {
    "name": "Acoustic Grand Piano",
    "wave": "sine",
    "velocity": 0.7,
    "attack": 0.003,
    "sustain": 0.05,
    "sustainPunch": 0.9,
    "decay": 0.45,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Bright Acoustic Piano",
    "wave": "sine",
    "velocity": 0.7,
    "attack": 0.003,
    "sustain": 0.05,
    "sustainPunch": 0.9,
    "decay": 0.45,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Electric Grand Piano",
    "wave": "sine",
    "velocity": 0.7,
    "attack": 0.003,
    "sustain": 0.05,
    "sustainPunch": 0.9,
    "decay": 0.45,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Honky-tonk Piano",
    "wave": "sine",
    "velocity": 0.7,
    "attack": 0.003,
    "sustain": 0.05,
    "sustainPunch": 0.9,
    "decay": 0.45,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Electric Piano 1",
    "wave": "sine",
    "velocity": 0.7,
    "attack": 0.003,
    "sustain": 0.05,
    "sustainPunch": 0.9,
    "decay": 0.45,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Electric Piano 2",
    "wave": "sine",
    "velocity": 0.7,
    "attack": 0.003,
    "sustain": 0.05,
    "sustainPunch": 0.9,
    "decay": 0.45,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Harpsichord",
    "wave": "square",
    "velocity": 0.8,
    "attack": 0.01,
    "sustain": 0.25,
    "sustainPunch": 0.3,
    "decay": 0.25,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Clavinet",
    "wave": "square",
    "velocity": 0.8,
    "attack": 0.01,
    "sustain": 0.25,
    "sustainPunch": 0.3,
    "decay": 0.25,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Celesta",
    "wave": "sine",
    "velocity": 0.7,
    "attack": 0.001,
    "sustain": 0.0,
    "sustainPunch": 1.2,
    "decay": 2.5,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Glockenspiel",
    "wave": "sine",
    "velocity": 0.7,
    "attack": 0.001,
    "sustain": 0.0,
    "sustainPunch": 1.2,
    "decay": 2.5,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Music Box",
    "wave": "sine",
    "velocity": 0.7,
    "attack": 0.01,
    "sustain": 0.25,
    "sustainPunch": 0.3,
    "decay": 0.25,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Vibraphone",
    "wave": "sine",
    "velocity": 0.7,
    "attack": 0.001,
    "sustain": 0.0,
    "sustainPunch": 1.2,
    "decay": 2.5,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Marimba",
    "wave": "sine",
    "velocity": 0.7,
    "attack": 0.01,
    "sustain": 0.25,
    "sustainPunch": 0.3,
    "decay": 0.25,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Xylophone",
    "wave": "sine",
    "velocity": 0.7,
    "attack": 0.01,
    "sustain": 0.25,
    "sustainPunch": 0.3,
    "decay": 0.25,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Tubular Bells",
    "wave": "sine",
    "velocity": 0.7,
    "attack": 0.001,
    "sustain": 0.0,
    "sustainPunch": 1.2,
    "decay": 2.5,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Dulcimer",
    "wave": "sine",
    "velocity": 0.7,
    "attack": 0.01,
    "sustain": 0.25,
    "sustainPunch": 0.3,
    "decay": 0.25,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Drawbar Organ",
    "wave": "square",
    "velocity": 0.8,
    "attack": 0.005,
    "sustain": 2.0,
    "sustainPunch": 0.0,
    "decay": 0.05,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Percussive Organ",
    "wave": "square",
    "velocity": 0.8,
    "attack": 0.005,
    "sustain": 2.0,
    "sustainPunch": 0.0,
    "decay": 0.05,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Rock Organ",
    "wave": "square",
    "velocity": 0.8,
    "attack": 0.005,
    "sustain": 2.0,
    "sustainPunch": 0.0,
    "decay": 0.05,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Church Organ",
    "wave": "square",
    "velocity": 0.8,
    "attack": 0.005,
    "sustain": 2.0,
    "sustainPunch": 0.0,
    "decay": 0.05,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Reed Organ",
    "wave": "square",
    "velocity": 0.8,
    "attack": 0.005,
    "sustain": 2.0,
    "sustainPunch": 0.0,
    "decay": 0.05,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Accordion",
    "wave": "square",
    "velocity": 0.8,
    "attack": 0.01,
    "sustain": 0.25,
    "sustainPunch": 0.3,
    "decay": 0.25,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Harmonica",
    "wave": "square",
    "velocity": 0.8,
    "attack": 0.01,
    "sustain": 0.25,
    "sustainPunch": 0.3,
    "decay": 0.25,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Tango Accordion",
    "wave": "square",
    "velocity": 0.8,
    "attack": 0.01,
    "sustain": 0.25,
    "sustainPunch": 0.3,
    "decay": 0.25,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Acoustic Guitar (nylon)",
    "wave": "sawtooth",
    "velocity": 0.85,
    "attack": 0.005,
    "sustain": 0.06,
    "sustainPunch": 0.8,
    "decay": 0.3,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Acoustic Guitar (steel)",
    "wave": "sawtooth",
    "velocity": 0.85,
    "attack": 0.005,
    "sustain": 0.06,
    "sustainPunch": 0.8,
    "decay": 0.3,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Electric Guitar (jazz)",
    "wave": "sawtooth",
    "velocity": 0.85,
    "attack": 0.005,
    "sustain": 0.06,
    "sustainPunch": 0.8,
    "decay": 0.3,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Electric Guitar (clean)",
    "wave": "sawtooth",
    "velocity": 0.85,
    "attack": 0.005,
    "sustain": 0.06,
    "sustainPunch": 0.8,
    "decay": 0.3,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Electric Guitar (muted)",
    "wave": "sawtooth",
    "velocity": 0.85,
    "attack": 0.005,
    "sustain": 0.06,
    "sustainPunch": 0.8,
    "decay": 0.3,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Overdriven Guitar",
    "wave": "sawtooth",
    "velocity": 0.85,
    "attack": 0.005,
    "sustain": 0.06,
    "sustainPunch": 0.8,
    "decay": 0.3,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Distortion Guitar",
    "wave": "sawtooth",
    "velocity": 0.85,
    "attack": 0.005,
    "sustain": 0.06,
    "sustainPunch": 0.8,
    "decay": 0.3,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Guitar Harmonics",
    "wave": "sawtooth",
    "velocity": 0.85,
    "attack": 0.005,
    "sustain": 0.06,
    "sustainPunch": 0.8,
    "decay": 0.3,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Acoustic Bass",
    "wave": "sawtooth",
    "velocity": 0.85,
    "attack": 0.005,
    "sustain": 0.06,
    "sustainPunch": 0.8,
    "decay": 0.3,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Electric Bass (finger)",
    "wave": "sawtooth",
    "velocity": 0.85,
    "attack": 0.005,
    "sustain": 0.06,
    "sustainPunch": 0.8,
    "decay": 0.3,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Electric Bass (pick)",
    "wave": "sawtooth",
    "velocity": 0.85,
    "attack": 0.005,
    "sustain": 0.06,
    "sustainPunch": 0.8,
    "decay": 0.3,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Fretless Bass",
    "wave": "sawtooth",
    "velocity": 0.85,
    "attack": 0.005,
    "sustain": 0.06,
    "sustainPunch": 0.8,
    "decay": 0.3,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Slap Bass 1",
    "wave": "sawtooth",
    "velocity": 0.85,
    "attack": 0.005,
    "sustain": 0.06,
    "sustainPunch": 0.8,
    "decay": 0.3,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Slap Bass 2",
    "wave": "sawtooth",
    "velocity": 0.85,
    "attack": 0.005,
    "sustain": 0.06,
    "sustainPunch": 0.8,
    "decay": 0.3,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Synth Bass 1",
    "wave": "sawtooth",
    "velocity": 0.85,
    "attack": 0.005,
    "sustain": 0.06,
    "sustainPunch": 0.8,
    "decay": 0.3,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Synth Bass 2",
    "wave": "sawtooth",
    "velocity": 0.85,
    "attack": 0.005,
    "sustain": 0.06,
    "sustainPunch": 0.8,
    "decay": 0.3,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Violin",
    "wave": "sawtooth",
    "velocity": 0.85,
    "attack": 0.1,
    "sustain": 1.2,
    "sustainPunch": 0.1,
    "decay": 0.35,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0.02,
    "vibratoRate": 5.5
  },
  {
    "name": "Viola",
    "wave": "sawtooth",
    "velocity": 0.85,
    "attack": 0.1,
    "sustain": 1.2,
    "sustainPunch": 0.1,
    "decay": 0.35,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0.02,
    "vibratoRate": 5.5
  },
  {
    "name": "Cello",
    "wave": "sawtooth",
    "velocity": 0.85,
    "attack": 0.1,
    "sustain": 1.2,
    "sustainPunch": 0.1,
    "decay": 0.35,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0.02,
    "vibratoRate": 5.5
  },
  {
    "name": "Contrabass",
    "wave": "sawtooth",
    "velocity": 0.85,
    "attack": 0.1,
    "sustain": 1.2,
    "sustainPunch": 0.1,
    "decay": 0.35,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Tremolo Strings",
    "wave": "sawtooth",
    "velocity": 0.85,
    "attack": 0.1,
    "sustain": 1.2,
    "sustainPunch": 0.1,
    "decay": 0.35,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Pizzicato Strings",
    "wave": "sawtooth",
    "velocity": 0.85,
    "attack": 0.1,
    "sustain": 1.2,
    "sustainPunch": 0.1,
    "decay": 0.35,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Orchestral Harp",
    "wave": "sawtooth",
    "velocity": 0.85,
    "attack": 0.01,
    "sustain": 0.25,
    "sustainPunch": 0.3,
    "decay": 0.25,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Timpani",
    "wave": "noise",
    "velocity": 0.9,
    "attack": 0.001,
    "sustain": 0.0,
    "sustainPunch": 1.0,
    "decay": 0.08,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "String Ensemble 1",
    "wave": "sawtooth",
    "velocity": 0.85,
    "attack": 0.1,
    "sustain": 1.2,
    "sustainPunch": 0.1,
    "decay": 0.35,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "String Ensemble 2",
    "wave": "sawtooth",
    "velocity": 0.85,
    "attack": 0.1,
    "sustain": 1.2,
    "sustainPunch": 0.1,
    "decay": 0.35,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Synth Strings 1",
    "wave": "sawtooth",
    "velocity": 0.85,
    "attack": 0.1,
    "sustain": 1.2,
    "sustainPunch": 0.1,
    "decay": 0.35,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Synth Strings 2",
    "wave": "sawtooth",
    "velocity": 0.85,
    "attack": 0.1,
    "sustain": 1.2,
    "sustainPunch": 0.1,
    "decay": 0.35,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Choir Aahs",
    "wave": "sine",
    "velocity": 0.7,
    "attack": 0.01,
    "sustain": 0.25,
    "sustainPunch": 0.3,
    "decay": 0.25,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Voice Oohs",
    "wave": "sine",
    "velocity": 0.7,
    "attack": 0.01,
    "sustain": 0.25,
    "sustainPunch": 0.3,
    "decay": 0.25,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Synth Choir",
    "wave": "sine",
    "velocity": 0.7,
    "attack": 0.01,
    "sustain": 0.25,
    "sustainPunch": 0.3,
    "decay": 0.25,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Orchestra Hit",
    "wave": "sawtooth",
    "velocity": 0.85,
    "attack": 0.01,
    "sustain": 0.25,
    "sustainPunch": 0.3,
    "decay": 0.25,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Trumpet",
    "wave": "sawtooth",
    "velocity": 0.85,
    "attack": 0.04,
    "sustain": 0.8,
    "sustainPunch": 0.4,
    "decay": 0.2,
    "freqRamp": 0.05,
    "freqDeltaRamp": 0.3,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Trombone",
    "wave": "sawtooth",
    "velocity": 0.85,
    "attack": 0.04,
    "sustain": 0.8,
    "sustainPunch": 0.4,
    "decay": 0.2,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Tuba",
    "wave": "sawtooth",
    "velocity": 0.85,
    "attack": 0.04,
    "sustain": 0.8,
    "sustainPunch": 0.4,
    "decay": 0.2,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Muted Trumpet",
    "wave": "square",
    "velocity": 0.8,
    "attack": 0.04,
    "sustain": 0.8,
    "sustainPunch": 0.4,
    "decay": 0.2,
    "freqRamp": 0.05,
    "freqDeltaRamp": 0.3,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "French Horn",
    "wave": "sawtooth",
    "velocity": 0.85,
    "attack": 0.04,
    "sustain": 0.8,
    "sustainPunch": 0.4,
    "decay": 0.2,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Brass Section",
    "wave": "sawtooth",
    "velocity": 0.85,
    "attack": 0.04,
    "sustain": 0.8,
    "sustainPunch": 0.4,
    "decay": 0.2,
    "freqRamp": 0.05,
    "freqDeltaRamp": 0.3,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Synth Brass 1",
    "wave": "sawtooth",
    "velocity": 0.85,
    "attack": 0.04,
    "sustain": 0.8,
    "sustainPunch": 0.4,
    "decay": 0.2,
    "freqRamp": 0.05,
    "freqDeltaRamp": 0.3,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Synth Brass 2",
    "wave": "square",
    "velocity": 0.8,
    "attack": 0.04,
    "sustain": 0.8,
    "sustainPunch": 0.4,
    "decay": 0.2,
    "freqRamp": 0.05,
    "freqDeltaRamp": 0.3,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Soprano Sax",
    "wave": "square",
    "velocity": 0.8,
    "attack": 0.01,
    "sustain": 0.25,
    "sustainPunch": 0.3,
    "decay": 0.25,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0.02,
    "vibratoRate": 5.5
  },
  {
    "name": "Alto Sax",
    "wave": "square",
    "velocity": 0.8,
    "attack": 0.01,
    "sustain": 0.25,
    "sustainPunch": 0.3,
    "decay": 0.25,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0.02,
    "vibratoRate": 5.5
  },
  {
    "name": "Tenor Sax",
    "wave": "square",
    "velocity": 0.8,
    "attack": 0.01,
    "sustain": 0.25,
    "sustainPunch": 0.3,
    "decay": 0.25,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0.02,
    "vibratoRate": 5.5
  },
  {
    "name": "Baritone Sax",
    "wave": "square",
    "velocity": 0.8,
    "attack": 0.01,
    "sustain": 0.25,
    "sustainPunch": 0.3,
    "decay": 0.25,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0.02,
    "vibratoRate": 5.5
  },
  {
    "name": "Oboe",
    "wave": "square",
    "velocity": 0.8,
    "attack": 0.01,
    "sustain": 0.25,
    "sustainPunch": 0.3,
    "decay": 0.25,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "English Horn",
    "wave": "square",
    "velocity": 0.8,
    "attack": 0.04,
    "sustain": 0.8,
    "sustainPunch": 0.4,
    "decay": 0.2,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Bassoon",
    "wave": "square",
    "velocity": 0.8,
    "attack": 0.005,
    "sustain": 0.06,
    "sustainPunch": 0.8,
    "decay": 0.3,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Clarinet",
    "wave": "square",
    "velocity": 0.8,
    "attack": 0.01,
    "sustain": 0.25,
    "sustainPunch": 0.3,
    "decay": 0.25,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Piccolo",
    "wave": "sine",
    "velocity": 0.7,
    "attack": 0.03,
    "sustain": 1.0,
    "sustainPunch": 0.05,
    "decay": 0.2,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Flute",
    "wave": "sine",
    "velocity": 0.7,
    "attack": 0.03,
    "sustain": 1.0,
    "sustainPunch": 0.05,
    "decay": 0.2,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0.02,
    "vibratoRate": 5.5
  },
  {
    "name": "Recorder",
    "wave": "sine",
    "velocity": 0.7,
    "attack": 0.03,
    "sustain": 1.0,
    "sustainPunch": 0.05,
    "decay": 0.2,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Pan Flute",
    "wave": "sine",
    "velocity": 0.7,
    "attack": 0.03,
    "sustain": 1.0,
    "sustainPunch": 0.05,
    "decay": 0.2,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0.02,
    "vibratoRate": 5.5
  },
  {
    "name": "Blown Bottle",
    "wave": "sine",
    "velocity": 0.7,
    "attack": 0.01,
    "sustain": 0.25,
    "sustainPunch": 0.3,
    "decay": 0.25,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Shakuhachi",
    "wave": "sine",
    "velocity": 0.7,
    "attack": 0.03,
    "sustain": 1.0,
    "sustainPunch": 0.05,
    "decay": 0.2,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Whistle",
    "wave": "sine",
    "velocity": 0.7,
    "attack": 0.03,
    "sustain": 1.0,
    "sustainPunch": 0.05,
    "decay": 0.2,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Ocarina",
    "wave": "sine",
    "velocity": 0.7,
    "attack": 0.03,
    "sustain": 1.0,
    "sustainPunch": 0.05,
    "decay": 0.2,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Lead 1 (square)",
    "wave": "square",
    "velocity": 0.8,
    "attack": 0.01,
    "sustain": 0.25,
    "sustainPunch": 0.3,
    "decay": 0.25,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Lead 2 (sawtooth)",
    "wave": "sawtooth",
    "velocity": 0.85,
    "attack": 0.01,
    "sustain": 0.25,
    "sustainPunch": 0.3,
    "decay": 0.25,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Lead 3 (calliope)",
    "wave": "square",
    "velocity": 0.8,
    "attack": 0.01,
    "sustain": 0.25,
    "sustainPunch": 0.3,
    "decay": 0.25,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Lead 4 (chiff)",
    "wave": "square",
    "velocity": 0.8,
    "attack": 0.01,
    "sustain": 0.25,
    "sustainPunch": 0.3,
    "decay": 0.25,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Lead 5 (charang)",
    "wave": "sawtooth",
    "velocity": 0.85,
    "attack": 0.01,
    "sustain": 0.25,
    "sustainPunch": 0.3,
    "decay": 0.25,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Lead 6 (voice)",
    "wave": "sine",
    "velocity": 0.7,
    "attack": 0.01,
    "sustain": 0.25,
    "sustainPunch": 0.3,
    "decay": 0.25,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Lead 7 (fifths)",
    "wave": "sawtooth",
    "velocity": 0.85,
    "attack": 0.01,
    "sustain": 0.25,
    "sustainPunch": 0.3,
    "decay": 0.25,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Lead 8 (bass+lead)",
    "wave": "sawtooth",
    "velocity": 0.85,
    "attack": 0.01,
    "sustain": 0.25,
    "sustainPunch": 0.3,
    "decay": 0.25,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Pad 1 (new age)",
    "wave": "sawtooth",
    "velocity": 0.85,
    "attack": 0.5,
    "sustain": 2.5,
    "sustainPunch": 0.0,
    "decay": 0.8,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Pad 2 (warm)",
    "wave": "sawtooth",
    "velocity": 0.85,
    "attack": 0.5,
    "sustain": 2.5,
    "sustainPunch": 0.0,
    "decay": 0.8,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Pad 3 (polysynth)",
    "wave": "sawtooth",
    "velocity": 0.85,
    "attack": 0.5,
    "sustain": 2.5,
    "sustainPunch": 0.0,
    "decay": 0.8,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Pad 4 (choir)",
    "wave": "sawtooth",
    "velocity": 0.85,
    "attack": 0.5,
    "sustain": 2.5,
    "sustainPunch": 0.0,
    "decay": 0.8,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Pad 5 (bowed)",
    "wave": "sawtooth",
    "velocity": 0.85,
    "attack": 0.5,
    "sustain": 2.5,
    "sustainPunch": 0.0,
    "decay": 0.8,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Pad 6 (metallic)",
    "wave": "sawtooth",
    "velocity": 0.85,
    "attack": 0.5,
    "sustain": 2.5,
    "sustainPunch": 0.0,
    "decay": 0.8,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Pad 7 (halo)",
    "wave": "sawtooth",
    "velocity": 0.85,
    "attack": 0.5,
    "sustain": 2.5,
    "sustainPunch": 0.0,
    "decay": 0.8,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Pad 8 (sweep)",
    "wave": "sawtooth",
    "velocity": 0.85,
    "attack": 0.5,
    "sustain": 2.5,
    "sustainPunch": 0.0,
    "decay": 0.8,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "FX 1 (rain)",
    "wave": "noise",
    "velocity": 0.9,
    "attack": 0.01,
    "sustain": 0.25,
    "sustainPunch": 0.3,
    "decay": 0.25,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "FX 2 (soundtrack)",
    "wave": "sawtooth",
    "velocity": 0.85,
    "attack": 0.01,
    "sustain": 0.25,
    "sustainPunch": 0.3,
    "decay": 0.25,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "FX 3 (crystal)",
    "wave": "sine",
    "velocity": 0.7,
    "attack": 0.01,
    "sustain": 0.25,
    "sustainPunch": 0.3,
    "decay": 0.25,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "FX 4 (atmosphere)",
    "wave": "noise",
    "velocity": 0.9,
    "attack": 0.01,
    "sustain": 0.25,
    "sustainPunch": 0.3,
    "decay": 0.25,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "FX 5 (brightness)",
    "wave": "sawtooth",
    "velocity": 0.85,
    "attack": 0.01,
    "sustain": 0.25,
    "sustainPunch": 0.3,
    "decay": 0.25,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "FX 6 (goblins)",
    "wave": "noise",
    "velocity": 0.9,
    "attack": 0.01,
    "sustain": 0.25,
    "sustainPunch": 0.3,
    "decay": 0.25,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "FX 7 (echoes)",
    "wave": "sine",
    "velocity": 0.7,
    "attack": 0.01,
    "sustain": 0.25,
    "sustainPunch": 0.3,
    "decay": 0.25,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "FX 8 (sci-fi)",
    "wave": "sawtooth",
    "velocity": 0.85,
    "attack": 0.01,
    "sustain": 0.25,
    "sustainPunch": 0.3,
    "decay": 0.25,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Sitar",
    "wave": "sawtooth",
    "velocity": 0.85,
    "attack": 0.01,
    "sustain": 0.25,
    "sustainPunch": 0.3,
    "decay": 0.25,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Banjo",
    "wave": "square",
    "velocity": 0.8,
    "attack": 0.01,
    "sustain": 0.25,
    "sustainPunch": 0.3,
    "decay": 0.25,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Shamisen",
    "wave": "square",
    "velocity": 0.8,
    "attack": 0.01,
    "sustain": 0.25,
    "sustainPunch": 0.3,
    "decay": 0.25,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Koto",
    "wave": "sine",
    "velocity": 0.7,
    "attack": 0.01,
    "sustain": 0.25,
    "sustainPunch": 0.3,
    "decay": 0.25,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Kalimba",
    "wave": "sine",
    "velocity": 0.7,
    "attack": 0.01,
    "sustain": 0.25,
    "sustainPunch": 0.3,
    "decay": 0.25,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Bagpipe",
    "wave": "square",
    "velocity": 0.8,
    "attack": 0.01,
    "sustain": 0.25,
    "sustainPunch": 0.3,
    "decay": 0.25,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Fiddle",
    "wave": "sawtooth",
    "velocity": 0.85,
    "attack": 0.01,
    "sustain": 0.25,
    "sustainPunch": 0.3,
    "decay": 0.25,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Shanai",
    "wave": "square",
    "velocity": 0.8,
    "attack": 0.01,
    "sustain": 0.25,
    "sustainPunch": 0.3,
    "decay": 0.25,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Tinkle Bell",
    "wave": "sine",
    "velocity": 0.7,
    "attack": 0.001,
    "sustain": 0.0,
    "sustainPunch": 1.2,
    "decay": 2.5,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Agogo",
    "wave": "noise",
    "velocity": 0.9,
    "attack": 0.01,
    "sustain": 0.25,
    "sustainPunch": 0.3,
    "decay": 0.25,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Steel Drums",
    "wave": "sine",
    "velocity": 0.7,
    "attack": 0.001,
    "sustain": 0.0,
    "sustainPunch": 1.0,
    "decay": 0.08,
    "freqRamp": 0.05,
    "freqDeltaRamp": -18,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Woodblock",
    "wave": "noise",
    "velocity": 0.9,
    "attack": 0.01,
    "sustain": 0.25,
    "sustainPunch": 0.3,
    "decay": 0.25,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Taiko Drum",
    "wave": "noise",
    "velocity": 0.9,
    "attack": 0.001,
    "sustain": 0.0,
    "sustainPunch": 1.0,
    "decay": 0.08,
    "freqRamp": 0.05,
    "freqDeltaRamp": -18,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Melodic Tom",
    "wave": "noise",
    "velocity": 0.9,
    "attack": 0.001,
    "sustain": 0.0,
    "sustainPunch": 1.0,
    "decay": 0.08,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Synth Drum",
    "wave": "noise",
    "velocity": 0.9,
    "attack": 0.001,
    "sustain": 0.0,
    "sustainPunch": 1.0,
    "decay": 0.08,
    "freqRamp": 0.05,
    "freqDeltaRamp": -18,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Reverse Cymbal",
    "wave": "noise",
    "velocity": 0.9,
    "attack": 0.01,
    "sustain": 0.25,
    "sustainPunch": 0.3,
    "decay": 0.25,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Guitar Fret Noise",
    "wave": "noise",
    "velocity": 0.9,
    "attack": 0.005,
    "sustain": 0.06,
    "sustainPunch": 0.8,
    "decay": 0.3,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Breath Noise",
    "wave": "noise",
    "velocity": 0.9,
    "attack": 0.01,
    "sustain": 0.25,
    "sustainPunch": 0.3,
    "decay": 0.25,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Seashore",
    "wave": "noise",
    "velocity": 0.9,
    "attack": 0.01,
    "sustain": 0.25,
    "sustainPunch": 0.3,
    "decay": 0.25,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Bird Tweet",
    "wave": "sine",
    "velocity": 0.7,
    "attack": 0.01,
    "sustain": 0.25,
    "sustainPunch": 0.3,
    "decay": 0.25,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Telephone Ring",
    "wave": "square",
    "velocity": 0.8,
    "attack": 0.01,
    "sustain": 0.25,
    "sustainPunch": 0.3,
    "decay": 0.25,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Helicopter",
    "wave": "noise",
    "velocity": 0.9,
    "attack": 0.001,
    "sustain": 0.0,
    "sustainPunch": 1.0,
    "decay": 0.08,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Applause",
    "wave": "noise",
    "velocity": 0.9,
    "attack": 0.001,
    "sustain": 0.0,
    "sustainPunch": 1.0,
    "decay": 0.08,
    "freqRamp": 0,
    "freqDeltaRamp": 0,
    "vibratoDepth": 0,
    "vibratoRate": 0
  },
  {
    "name": "Gunshot",
    "wave": "noise",
    "velocity": 0.9,
    "attack": 0.001,
    "sustain": 0.0,
    "sustainPunch": 1.0,
    "decay": 0.08,
    "freqRamp": 0.05,
    "freqDeltaRamp": -18,
    "vibratoDepth": 0,
    "vibratoRate": 0
  }
];

export function get_instrument(index: number) {
    return instrument_map[index];
};