import {
	SoundGeneratorParameters,
	SoundGeneratorParametersWaveType,
} from '@/generated/proto';

export interface Instrument {
	name: string;
	volume: number;
	parameters: Required<
		Pick<
			SoundGeneratorParameters,
			| 'waveType'
			| 'envelopeAttack'
			| 'envelopeSustain'
			| 'envelopePunch'
			| 'envelopeRelease'
			| 'frequencyRamp'
			| 'frequencyDeltaRamp'
			| 'vibratoStrength'
			| 'vibratoSpeed'
		>
	>;
}

export interface Drum {
	name: string;
	volume: number;
	parameters: Required<
		Pick<
			SoundGeneratorParameters,
			| 'envelopeAttack'
			| 'envelopeSustain'
			| 'envelopePunch'
			| 'envelopeRelease'
			| 'frequencyRamp'
			| 'frequencyDeltaRamp'
		>
	>;
}

const instrument_map: Instrument[] = [
	{
		name: 'Acoustic Grand Piano',
		volume: 0.7,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sine,
			envelopeAttack: 0.003,
			envelopeSustain: 0.05,
			envelopeRelease: 0.45,
			envelopePunch: 0.9,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Bright Acoustic Piano',
		volume: 0.7,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sine,
			envelopeAttack: 0.003,
			envelopeSustain: 0.05,
			envelopeRelease: 0.45,
			envelopePunch: 0.9,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Electric Grand Piano',
		volume: 0.7,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sine,
			envelopeAttack: 0.003,
			envelopeSustain: 0.05,
			envelopeRelease: 0.45,
			envelopePunch: 0.9,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Honky-tonk Piano',
		volume: 0.7,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sine,
			envelopeAttack: 0.003,
			envelopeSustain: 0.05,
			envelopeRelease: 0.45,
			envelopePunch: 0.9,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Electric Piano 1',
		volume: 0.7,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sine,
			envelopeAttack: 0.003,
			envelopeSustain: 0.05,
			envelopeRelease: 0.45,
			envelopePunch: 0.9,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Electric Piano 2',
		volume: 0.7,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sine,
			envelopeAttack: 0.003,
			envelopeSustain: 0.05,
			envelopeRelease: 0.45,
			envelopePunch: 0.9,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Harpsichord',
		volume: 0.8,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Square,
			envelopeAttack: 0.01,
			envelopeSustain: 0.25,
			envelopeRelease: 0.25,
			envelopePunch: 0.3,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Clavinet',
		volume: 0.8,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Square,
			envelopeAttack: 0.01,
			envelopeSustain: 0.25,
			envelopeRelease: 0.25,
			envelopePunch: 0.3,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Celesta',
		volume: 0.7,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sine,
			envelopeAttack: 0.001,
			envelopeSustain: 0,
			envelopeRelease: 2.5,
			envelopePunch: 1.2,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Glockenspiel',
		volume: 0.7,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sine,
			envelopeAttack: 0.001,
			envelopeSustain: 0,
			envelopeRelease: 2.5,
			envelopePunch: 1.2,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Music Box',
		volume: 0.7,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sine,
			envelopeAttack: 0.01,
			envelopeSustain: 0.25,
			envelopeRelease: 0.25,
			envelopePunch: 0.3,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Vibraphone',
		volume: 0.7,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sine,
			envelopeAttack: 0.001,
			envelopeSustain: 0,
			envelopeRelease: 2.5,
			envelopePunch: 1.2,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Marimba',
		volume: 0.7,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sine,
			envelopeAttack: 0.01,
			envelopeSustain: 0.25,
			envelopeRelease: 0.25,
			envelopePunch: 0.3,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Xylophone',
		volume: 0.7,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sine,
			envelopeAttack: 0.01,
			envelopeSustain: 0.25,
			envelopeRelease: 0.25,
			envelopePunch: 0.3,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Tubular Bells',
		volume: 0.7,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sine,
			envelopeAttack: 0.001,
			envelopeSustain: 0,
			envelopeRelease: 2.5,
			envelopePunch: 1.2,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Dulcimer',
		volume: 0.7,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sine,
			envelopeAttack: 0.01,
			envelopeSustain: 0.25,
			envelopeRelease: 0.25,
			envelopePunch: 0.3,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Drawbar Organ',
		volume: 0.8,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Square,
			envelopeAttack: 0.005,
			envelopeSustain: 2,
			envelopeRelease: 0.05,
			envelopePunch: 0,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Percussive Organ',
		volume: 0.8,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Square,
			envelopeAttack: 0.005,
			envelopeSustain: 2,
			envelopeRelease: 0.05,
			envelopePunch: 0,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Rock Organ',
		volume: 0.8,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Square,
			envelopeAttack: 0.005,
			envelopeSustain: 2,
			envelopeRelease: 0.05,
			envelopePunch: 0,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Church Organ',
		volume: 0.8,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Square,
			envelopeAttack: 0.005,
			envelopeSustain: 2,
			envelopeRelease: 0.05,
			envelopePunch: 0,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Reed Organ',
		volume: 0.8,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Square,
			envelopeAttack: 0.005,
			envelopeSustain: 2,
			envelopeRelease: 0.05,
			envelopePunch: 0,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Accordion',
		volume: 0.8,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Square,
			envelopeAttack: 0.01,
			envelopeSustain: 0.25,
			envelopeRelease: 0.25,
			envelopePunch: 0.3,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Harmonica',
		volume: 0.8,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Square,
			envelopeAttack: 0.01,
			envelopeSustain: 0.25,
			envelopeRelease: 0.25,
			envelopePunch: 0.3,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Tango Accordion',
		volume: 0.8,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Square,
			envelopeAttack: 0.01,
			envelopeSustain: 0.25,
			envelopeRelease: 0.25,
			envelopePunch: 0.3,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Acoustic Guitar (nylon)',
		volume: 0.85,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sawtooth,
			envelopeAttack: 0.005,
			envelopeSustain: 0.06,
			envelopeRelease: 0.3,
			envelopePunch: 0.8,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Acoustic Guitar (steel)',
		volume: 0.85,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sawtooth,
			envelopeAttack: 0.005,
			envelopeSustain: 0.06,
			envelopeRelease: 0.3,
			envelopePunch: 0.8,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Electric Guitar (jazz)',
		volume: 0.85,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sawtooth,
			envelopeAttack: 0.005,
			envelopeSustain: 0.06,
			envelopeRelease: 0.3,
			envelopePunch: 0.8,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Electric Guitar (clean)',
		volume: 0.85,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sawtooth,
			envelopeAttack: 0.005,
			envelopeSustain: 0.06,
			envelopeRelease: 0.3,
			envelopePunch: 0.8,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Electric Guitar (muted)',
		volume: 0.85,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sawtooth,
			envelopeAttack: 0.005,
			envelopeSustain: 0.06,
			envelopeRelease: 0.3,
			envelopePunch: 0.8,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Overdriven Guitar',
		volume: 0.85,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sawtooth,
			envelopeAttack: 0.005,
			envelopeSustain: 0.06,
			envelopeRelease: 0.3,
			envelopePunch: 0.8,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Distortion Guitar',
		volume: 0.85,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sawtooth,
			envelopeAttack: 0.005,
			envelopeSustain: 0.06,
			envelopeRelease: 0.3,
			envelopePunch: 0.8,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Guitar Harmonics',
		volume: 0.85,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sawtooth,
			envelopeAttack: 0.005,
			envelopeSustain: 0.06,
			envelopeRelease: 0.3,
			envelopePunch: 0.8,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Acoustic Bass',
		volume: 0.85,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sawtooth,
			envelopeAttack: 0.005,
			envelopeSustain: 0.06,
			envelopeRelease: 0.3,
			envelopePunch: 0.8,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Electric Bass (finger)',
		volume: 0.85,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sawtooth,
			envelopeAttack: 0.005,
			envelopeSustain: 0.06,
			envelopeRelease: 0.3,
			envelopePunch: 0.8,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Electric Bass (pick)',
		volume: 0.85,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sawtooth,
			envelopeAttack: 0.005,
			envelopeSustain: 0.06,
			envelopeRelease: 0.3,
			envelopePunch: 0.8,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Fretless Bass',
		volume: 0.85,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sawtooth,
			envelopeAttack: 0.005,
			envelopeSustain: 0.06,
			envelopeRelease: 0.3,
			envelopePunch: 0.8,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Slap Bass 1',
		volume: 0.85,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sawtooth,
			envelopeAttack: 0.005,
			envelopeSustain: 0.06,
			envelopeRelease: 0.3,
			envelopePunch: 0.8,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Slap Bass 2',
		volume: 0.85,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sawtooth,
			envelopeAttack: 0.005,
			envelopeSustain: 0.06,
			envelopeRelease: 0.3,
			envelopePunch: 0.8,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Synth Bass 1',
		volume: 0.85,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sawtooth,
			envelopeAttack: 0.005,
			envelopeSustain: 0.06,
			envelopeRelease: 0.3,
			envelopePunch: 0.8,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Synth Bass 2',
		volume: 0.85,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sawtooth,
			envelopeAttack: 0.005,
			envelopeSustain: 0.06,
			envelopeRelease: 0.3,
			envelopePunch: 0.8,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Violin',
		volume: 0.85,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sawtooth,
			envelopeAttack: 0.1,
			envelopeSustain: 1.2,
			envelopeRelease: 0.35,
			envelopePunch: 0.1,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0.02,
			vibratoSpeed: 5.5,
		},
	},
	{
		name: 'Viola',
		volume: 0.85,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sawtooth,
			envelopeAttack: 0.1,
			envelopeSustain: 1.2,
			envelopeRelease: 0.35,
			envelopePunch: 0.1,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0.02,
			vibratoSpeed: 5.5,
		},
	},
	{
		name: 'Cello',
		volume: 0.85,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sawtooth,
			envelopeAttack: 0.1,
			envelopeSustain: 1.2,
			envelopeRelease: 0.35,
			envelopePunch: 0.1,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0.02,
			vibratoSpeed: 5.5,
		},
	},
	{
		name: 'Contrabass',
		volume: 0.85,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sawtooth,
			envelopeAttack: 0.1,
			envelopeSustain: 1.2,
			envelopeRelease: 0.35,
			envelopePunch: 0.1,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Tremolo Strings',
		volume: 0.85,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sawtooth,
			envelopeAttack: 0.1,
			envelopeSustain: 1.2,
			envelopeRelease: 0.35,
			envelopePunch: 0.1,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Pizzicato Strings',
		volume: 0.85,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sawtooth,
			envelopeAttack: 0.1,
			envelopeSustain: 1.2,
			envelopeRelease: 0.35,
			envelopePunch: 0.1,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Orchestral Harp',
		volume: 0.85,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sawtooth,
			envelopeAttack: 0.01,
			envelopeSustain: 0.25,
			envelopeRelease: 0.25,
			envelopePunch: 0.3,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Timpani',
		volume: 0.9,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Noise,
			envelopeAttack: 0.001,
			envelopeSustain: 0,
			envelopeRelease: 0.08,
			envelopePunch: 1,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'String Ensemble 1',
		volume: 0.85,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sawtooth,
			envelopeAttack: 0.1,
			envelopeSustain: 1.2,
			envelopeRelease: 0.35,
			envelopePunch: 0.1,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'String Ensemble 2',
		volume: 0.85,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sawtooth,
			envelopeAttack: 0.1,
			envelopeSustain: 1.2,
			envelopeRelease: 0.35,
			envelopePunch: 0.1,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Synth Strings 1',
		volume: 0.85,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sawtooth,
			envelopeAttack: 0.1,
			envelopeSustain: 1.2,
			envelopeRelease: 0.35,
			envelopePunch: 0.1,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Synth Strings 2',
		volume: 0.85,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sawtooth,
			envelopeAttack: 0.1,
			envelopeSustain: 1.2,
			envelopeRelease: 0.35,
			envelopePunch: 0.1,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Choir Aahs',
		volume: 0.7,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sine,
			envelopeAttack: 0.01,
			envelopeSustain: 0.25,
			envelopeRelease: 0.25,
			envelopePunch: 0.3,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Voice Oohs',
		volume: 0.7,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sine,
			envelopeAttack: 0.01,
			envelopeSustain: 0.25,
			envelopeRelease: 0.25,
			envelopePunch: 0.3,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Synth Choir',
		volume: 0.7,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sine,
			envelopeAttack: 0.01,
			envelopeSustain: 0.25,
			envelopeRelease: 0.25,
			envelopePunch: 0.3,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Orchestra Hit',
		volume: 0.85,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sawtooth,
			envelopeAttack: 0.01,
			envelopeSustain: 0.25,
			envelopeRelease: 0.25,
			envelopePunch: 0.3,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Trumpet',
		volume: 0.85,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sawtooth,
			envelopeAttack: 0.04,
			envelopeSustain: 0.8,
			envelopeRelease: 0.2,
			envelopePunch: 0.4,
			frequencyRamp: 0.05,
			frequencyDeltaRamp: 0.3,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Trombone',
		volume: 0.85,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sawtooth,
			envelopeAttack: 0.04,
			envelopeSustain: 0.8,
			envelopeRelease: 0.2,
			envelopePunch: 0.4,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Tuba',
		volume: 0.85,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sawtooth,
			envelopeAttack: 0.04,
			envelopeSustain: 0.8,
			envelopeRelease: 0.2,
			envelopePunch: 0.4,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Muted Trumpet',
		volume: 0.8,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Square,
			envelopeAttack: 0.04,
			envelopeSustain: 0.8,
			envelopeRelease: 0.2,
			envelopePunch: 0.4,
			frequencyRamp: 0.05,
			frequencyDeltaRamp: 0.3,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'French Horn',
		volume: 0.85,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sawtooth,
			envelopeAttack: 0.04,
			envelopeSustain: 0.8,
			envelopeRelease: 0.2,
			envelopePunch: 0.4,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Brass Section',
		volume: 0.85,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sawtooth,
			envelopeAttack: 0.04,
			envelopeSustain: 0.8,
			envelopeRelease: 0.2,
			envelopePunch: 0.4,
			frequencyRamp: 0.05,
			frequencyDeltaRamp: 0.3,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Synth Brass 1',
		volume: 0.85,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sawtooth,
			envelopeAttack: 0.04,
			envelopeSustain: 0.8,
			envelopeRelease: 0.2,
			envelopePunch: 0.4,
			frequencyRamp: 0.05,
			frequencyDeltaRamp: 0.3,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Synth Brass 2',
		volume: 0.8,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Square,
			envelopeAttack: 0.04,
			envelopeSustain: 0.8,
			envelopeRelease: 0.2,
			envelopePunch: 0.4,
			frequencyRamp: 0.05,
			frequencyDeltaRamp: 0.3,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Soprano Sax',
		volume: 0.8,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Square,
			envelopeAttack: 0.01,
			envelopeSustain: 0.25,
			envelopeRelease: 0.25,
			envelopePunch: 0.3,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0.02,
			vibratoSpeed: 5.5,
		},
	},
	{
		name: 'Alto Sax',
		volume: 0.8,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Square,
			envelopeAttack: 0.01,
			envelopeSustain: 0.25,
			envelopeRelease: 0.25,
			envelopePunch: 0.3,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0.02,
			vibratoSpeed: 5.5,
		},
	},
	{
		name: 'Tenor Sax',
		volume: 0.8,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Square,
			envelopeAttack: 0.01,
			envelopeSustain: 0.25,
			envelopeRelease: 0.25,
			envelopePunch: 0.3,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0.02,
			vibratoSpeed: 5.5,
		},
	},
	{
		name: 'Baritone Sax',
		volume: 0.8,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Square,
			envelopeAttack: 0.01,
			envelopeSustain: 0.25,
			envelopeRelease: 0.25,
			envelopePunch: 0.3,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0.02,
			vibratoSpeed: 5.5,
		},
	},
	{
		name: 'Oboe',
		volume: 0.8,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Square,
			envelopeAttack: 0.01,
			envelopeSustain: 0.25,
			envelopeRelease: 0.25,
			envelopePunch: 0.3,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'English Horn',
		volume: 0.8,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Square,
			envelopeAttack: 0.04,
			envelopeSustain: 0.8,
			envelopeRelease: 0.2,
			envelopePunch: 0.4,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Bassoon',
		volume: 0.8,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Square,
			envelopeAttack: 0.005,
			envelopeSustain: 0.06,
			envelopeRelease: 0.3,
			envelopePunch: 0.8,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Clarinet',
		volume: 0.8,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Square,
			envelopeAttack: 0.01,
			envelopeSustain: 0.25,
			envelopeRelease: 0.25,
			envelopePunch: 0.3,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Piccolo',
		volume: 0.7,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sine,
			envelopeAttack: 0.03,
			envelopeSustain: 1,
			envelopeRelease: 0.2,
			envelopePunch: 0.05,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Flute',
		volume: 0.7,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sine,
			envelopeAttack: 0.03,
			envelopeSustain: 1,
			envelopeRelease: 0.2,
			envelopePunch: 0.05,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0.02,
			vibratoSpeed: 5.5,
		},
	},
	{
		name: 'Recorder',
		volume: 0.7,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sine,
			envelopeAttack: 0.03,
			envelopeSustain: 1,
			envelopeRelease: 0.2,
			envelopePunch: 0.05,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Pan Flute',
		volume: 0.7,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sine,
			envelopeAttack: 0.03,
			envelopeSustain: 1,
			envelopeRelease: 0.2,
			envelopePunch: 0.05,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0.02,
			vibratoSpeed: 5.5,
		},
	},
	{
		name: 'Blown Bottle',
		volume: 0.7,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sine,
			envelopeAttack: 0.01,
			envelopeSustain: 0.25,
			envelopeRelease: 0.25,
			envelopePunch: 0.3,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Shakuhachi',
		volume: 0.7,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sine,
			envelopeAttack: 0.03,
			envelopeSustain: 1,
			envelopeRelease: 0.2,
			envelopePunch: 0.05,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Whistle',
		volume: 0.7,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sine,
			envelopeAttack: 0.03,
			envelopeSustain: 1,
			envelopeRelease: 0.2,
			envelopePunch: 0.05,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Ocarina',
		volume: 0.7,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sine,
			envelopeAttack: 0.03,
			envelopeSustain: 1,
			envelopeRelease: 0.2,
			envelopePunch: 0.05,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Lead 1 (square)',
		volume: 0.8,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Square,
			envelopeAttack: 0.01,
			envelopeSustain: 0.25,
			envelopeRelease: 0.25,
			envelopePunch: 0.3,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Lead 2 (sawtooth)',
		volume: 0.85,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sawtooth,
			envelopeAttack: 0.01,
			envelopeSustain: 0.25,
			envelopeRelease: 0.25,
			envelopePunch: 0.3,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Lead 3 (calliope)',
		volume: 0.8,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Square,
			envelopeAttack: 0.01,
			envelopeSustain: 0.25,
			envelopeRelease: 0.25,
			envelopePunch: 0.3,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Lead 4 (chiff)',
		volume: 0.8,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Square,
			envelopeAttack: 0.01,
			envelopeSustain: 0.25,
			envelopeRelease: 0.25,
			envelopePunch: 0.3,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Lead 5 (charang)',
		volume: 0.85,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sawtooth,
			envelopeAttack: 0.01,
			envelopeSustain: 0.25,
			envelopeRelease: 0.25,
			envelopePunch: 0.3,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Lead 6 (voice)',
		volume: 0.7,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sine,
			envelopeAttack: 0.01,
			envelopeSustain: 0.25,
			envelopeRelease: 0.25,
			envelopePunch: 0.3,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Lead 7 (fifths)',
		volume: 0.85,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sawtooth,
			envelopeAttack: 0.01,
			envelopeSustain: 0.25,
			envelopeRelease: 0.25,
			envelopePunch: 0.3,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Lead 8 (bass+lead)',
		volume: 0.85,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sawtooth,
			envelopeAttack: 0.01,
			envelopeSustain: 0.25,
			envelopeRelease: 0.25,
			envelopePunch: 0.3,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Pad 1 (new age)',
		volume: 0.85,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sawtooth,
			envelopeAttack: 0.5,
			envelopeSustain: 2.5,
			envelopeRelease: 0.8,
			envelopePunch: 0,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Pad 2 (warm)',
		volume: 0.85,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sawtooth,
			envelopeAttack: 0.5,
			envelopeSustain: 2.5,
			envelopeRelease: 0.8,
			envelopePunch: 0,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Pad 3 (polysynth)',
		volume: 0.85,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sawtooth,
			envelopeAttack: 0.5,
			envelopeSustain: 2.5,
			envelopeRelease: 0.8,
			envelopePunch: 0,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Pad 4 (choir)',
		volume: 0.85,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sawtooth,
			envelopeAttack: 0.5,
			envelopeSustain: 2.5,
			envelopeRelease: 0.8,
			envelopePunch: 0,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Pad 5 (bowed)',
		volume: 0.85,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sawtooth,
			envelopeAttack: 0.5,
			envelopeSustain: 2.5,
			envelopeRelease: 0.8,
			envelopePunch: 0,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Pad 6 (metallic)',
		volume: 0.85,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sawtooth,
			envelopeAttack: 0.5,
			envelopeSustain: 2.5,
			envelopeRelease: 0.8,
			envelopePunch: 0,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Pad 7 (halo)',
		volume: 0.85,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sawtooth,
			envelopeAttack: 0.5,
			envelopeSustain: 2.5,
			envelopeRelease: 0.8,
			envelopePunch: 0,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Pad 8 (sweep)',
		volume: 0.85,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sawtooth,
			envelopeAttack: 0.5,
			envelopeSustain: 2.5,
			envelopeRelease: 0.8,
			envelopePunch: 0,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'FX 1 (rain)',
		volume: 0.9,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Noise,
			envelopeAttack: 0.01,
			envelopeSustain: 0.25,
			envelopeRelease: 0.25,
			envelopePunch: 0.3,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'FX 2 (soundtrack)',
		volume: 0.85,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sawtooth,
			envelopeAttack: 0.01,
			envelopeSustain: 0.25,
			envelopeRelease: 0.25,
			envelopePunch: 0.3,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'FX 3 (crystal)',
		volume: 0.7,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sine,
			envelopeAttack: 0.01,
			envelopeSustain: 0.25,
			envelopeRelease: 0.25,
			envelopePunch: 0.3,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'FX 4 (atmosphere)',
		volume: 0.9,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Noise,
			envelopeAttack: 0.01,
			envelopeSustain: 0.25,
			envelopeRelease: 0.25,
			envelopePunch: 0.3,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'FX 5 (brightness)',
		volume: 0.85,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sawtooth,
			envelopeAttack: 0.01,
			envelopeSustain: 0.25,
			envelopeRelease: 0.25,
			envelopePunch: 0.3,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'FX 6 (goblins)',
		volume: 0.9,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Noise,
			envelopeAttack: 0.01,
			envelopeSustain: 0.25,
			envelopeRelease: 0.25,
			envelopePunch: 0.3,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'FX 7 (echoes)',
		volume: 0.7,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sine,
			envelopeAttack: 0.01,
			envelopeSustain: 0.25,
			envelopeRelease: 0.25,
			envelopePunch: 0.3,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'FX 8 (sci-fi)',
		volume: 0.85,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sawtooth,
			envelopeAttack: 0.01,
			envelopeSustain: 0.25,
			envelopeRelease: 0.25,
			envelopePunch: 0.3,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Sitar',
		volume: 0.85,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sawtooth,
			envelopeAttack: 0.01,
			envelopeSustain: 0.25,
			envelopeRelease: 0.25,
			envelopePunch: 0.3,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Banjo',
		volume: 0.8,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Square,
			envelopeAttack: 0.01,
			envelopeSustain: 0.25,
			envelopeRelease: 0.25,
			envelopePunch: 0.3,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Shamisen',
		volume: 0.8,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Square,
			envelopeAttack: 0.01,
			envelopeSustain: 0.25,
			envelopeRelease: 0.25,
			envelopePunch: 0.3,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Koto',
		volume: 0.7,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sine,
			envelopeAttack: 0.01,
			envelopeSustain: 0.25,
			envelopeRelease: 0.25,
			envelopePunch: 0.3,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Kalimba',
		volume: 0.7,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sine,
			envelopeAttack: 0.01,
			envelopeSustain: 0.25,
			envelopeRelease: 0.25,
			envelopePunch: 0.3,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Bagpipe',
		volume: 0.8,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Square,
			envelopeAttack: 0.01,
			envelopeSustain: 0.25,
			envelopeRelease: 0.25,
			envelopePunch: 0.3,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Fiddle',
		volume: 0.85,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sawtooth,
			envelopeAttack: 0.01,
			envelopeSustain: 0.25,
			envelopeRelease: 0.25,
			envelopePunch: 0.3,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Shanai',
		volume: 0.8,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Square,
			envelopeAttack: 0.01,
			envelopeSustain: 0.25,
			envelopeRelease: 0.25,
			envelopePunch: 0.3,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Tinkle Bell',
		volume: 0.7,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sine,
			envelopeAttack: 0.001,
			envelopeSustain: 0,
			envelopeRelease: 2.5,
			envelopePunch: 1.2,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Agogo',
		volume: 0.9,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Noise,
			envelopeAttack: 0.01,
			envelopeSustain: 0.25,
			envelopeRelease: 0.25,
			envelopePunch: 0.3,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Steel Drums',
		volume: 0.7,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sine,
			envelopeAttack: 0.001,
			envelopeSustain: 0,
			envelopeRelease: 0.08,
			envelopePunch: 1,
			frequencyRamp: 0.05,
			frequencyDeltaRamp: -18,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Woodblock',
		volume: 0.9,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Noise,
			envelopeAttack: 0.01,
			envelopeSustain: 0.25,
			envelopeRelease: 0.25,
			envelopePunch: 0.3,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Taiko Drum',
		volume: 0.9,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Noise,
			envelopeAttack: 0.001,
			envelopeSustain: 0,
			envelopeRelease: 0.08,
			envelopePunch: 1,
			frequencyRamp: 0.05,
			frequencyDeltaRamp: -18,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Melodic Tom',
		volume: 0.9,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Noise,
			envelopeAttack: 0.001,
			envelopeSustain: 0,
			envelopeRelease: 0.08,
			envelopePunch: 1,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Synth Drum',
		volume: 0.9,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Noise,
			envelopeAttack: 0.001,
			envelopeSustain: 0,
			envelopeRelease: 0.08,
			envelopePunch: 1,
			frequencyRamp: 0.05,
			frequencyDeltaRamp: -18,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Reverse Cymbal',
		volume: 0.9,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Noise,
			envelopeAttack: 0.01,
			envelopeSustain: 0.25,
			envelopeRelease: 0.25,
			envelopePunch: 0.3,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Guitar Fret Noise',
		volume: 0.9,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Noise,
			envelopeAttack: 0.005,
			envelopeSustain: 0.06,
			envelopeRelease: 0.3,
			envelopePunch: 0.8,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Breath Noise',
		volume: 0.9,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Noise,
			envelopeAttack: 0.01,
			envelopeSustain: 0.25,
			envelopeRelease: 0.25,
			envelopePunch: 0.3,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Seashore',
		volume: 0.9,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Noise,
			envelopeAttack: 0.01,
			envelopeSustain: 0.25,
			envelopeRelease: 0.25,
			envelopePunch: 0.3,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Bird Tweet',
		volume: 0.7,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Sine,
			envelopeAttack: 0.01,
			envelopeSustain: 0.25,
			envelopeRelease: 0.25,
			envelopePunch: 0.3,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Telephone Ring',
		volume: 0.8,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Square,
			envelopeAttack: 0.01,
			envelopeSustain: 0.25,
			envelopeRelease: 0.25,
			envelopePunch: 0.3,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Helicopter',
		volume: 0.9,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Noise,
			envelopeAttack: 0.001,
			envelopeSustain: 0,
			envelopeRelease: 0.08,
			envelopePunch: 1,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Applause',
		volume: 0.9,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Noise,
			envelopeAttack: 0.001,
			envelopeSustain: 0,
			envelopeRelease: 0.08,
			envelopePunch: 1,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
	{
		name: 'Gunshot',
		volume: 0.9,
		parameters: {
			waveType: SoundGeneratorParametersWaveType.Noise,
			envelopeAttack: 0.001,
			envelopeSustain: 0,
			envelopeRelease: 0.08,
			envelopePunch: 1,
			frequencyRamp: 0.05,
			frequencyDeltaRamp: -18,
			vibratoStrength: 0,
			vibratoSpeed: 0,
		},
	},
];

const percussion_map: Drum[] = [
	{
		name: 'Acoustic Bass Drum',
		volume: 1,
		parameters: {
			envelopeAttack: 0,
			envelopeSustain: 0,
			envelopeRelease: 0.22,
			envelopePunch: 1.2,
			frequencyRamp: 0.06,
			frequencyDeltaRamp: -28,
		},
	},
	{
		name: 'Bass Drum 1',
		volume: 1,
		parameters: {
			envelopeAttack: 0,
			envelopeSustain: 0,
			envelopeRelease: 0.2,
			envelopePunch: 1.15,
			frequencyRamp: 0.05,
			frequencyDeltaRamp: -24,
		},
	},
	{
		name: 'Side Stick',
		volume: 0.85,
		parameters: {
			envelopeAttack: 0,
			envelopeSustain: 0,
			envelopeRelease: 0.035,
			envelopePunch: 0.95,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
		},
	},
	{
		name: 'Acoustic Snare',
		volume: 0.98,
		parameters: {
			envelopeAttack: 0,
			envelopeSustain: 0,
			envelopeRelease: 0.12,
			envelopePunch: 1.1,
			frequencyRamp: 0.035,
			frequencyDeltaRamp: -12,
		},
	},
	{
		name: 'Hand Clap',
		volume: 0.92,
		parameters: {
			envelopeAttack: 0,
			envelopeSustain: 0.02,
			envelopeRelease: 0.16,
			envelopePunch: 1.25,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
		},
	},
	{
		name: 'Electric Snare',
		volume: 0.95,
		parameters: {
			envelopeAttack: 0,
			envelopeSustain: 0,
			envelopeRelease: 0.1,
			envelopePunch: 1.05,
			frequencyRamp: 0.03,
			frequencyDeltaRamp: -10,
		},
	},
	{
		name: 'Low Floor Tom',
		volume: 0.96,
		parameters: {
			envelopeAttack: 0,
			envelopeSustain: 0,
			envelopeRelease: 0.18,
			envelopePunch: 1,
			frequencyRamp: 0.05,
			frequencyDeltaRamp: -18,
		},
	},
	{
		name: 'Closed Hi-Hat',
		volume: 0.88,
		parameters: {
			envelopeAttack: 0,
			envelopeSustain: 0,
			envelopeRelease: 0.045,
			envelopePunch: 1.05,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
		},
	},
	{
		name: 'High Floor Tom',
		volume: 0.95,
		parameters: {
			envelopeAttack: 0,
			envelopeSustain: 0,
			envelopeRelease: 0.16,
			envelopePunch: 1,
			frequencyRamp: 0.048,
			frequencyDeltaRamp: -17,
		},
	},
	{
		name: 'Pedal Hi-Hat',
		volume: 0.82,
		parameters: {
			envelopeAttack: 0,
			envelopeSustain: 0,
			envelopeRelease: 0.035,
			envelopePunch: 0.95,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
		},
	},
	{
		name: 'Low Tom',
		volume: 0.94,
		parameters: {
			envelopeAttack: 0,
			envelopeSustain: 0,
			envelopeRelease: 0.15,
			envelopePunch: 1,
			frequencyRamp: 0.045,
			frequencyDeltaRamp: -16,
		},
	},
	{
		name: 'Open Hi-Hat',
		volume: 0.92,
		parameters: {
			envelopeAttack: 0,
			envelopeSustain: 0,
			envelopeRelease: 0.42,
			envelopePunch: 1.1,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
		},
	},
	{
		name: 'Low-Mid Tom',
		volume: 0.93,
		parameters: {
			envelopeAttack: 0,
			envelopeSustain: 0,
			envelopeRelease: 0.14,
			envelopePunch: 1,
			frequencyRamp: 0.042,
			frequencyDeltaRamp: -15,
		},
	},
	{
		name: 'Hi-Mid Tom',
		volume: 0.92,
		parameters: {
			envelopeAttack: 0,
			envelopeSustain: 0,
			envelopeRelease: 0.13,
			envelopePunch: 1,
			frequencyRamp: 0.04,
			frequencyDeltaRamp: -14,
		},
	},
	{
		name: 'Crash Cymbal 1',
		volume: 1,
		parameters: {
			envelopeAttack: 0,
			envelopeSustain: 0,
			envelopeRelease: 1.8,
			envelopePunch: 1.15,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
		},
	},
	{
		name: 'High Tom',
		volume: 0.9,
		parameters: {
			envelopeAttack: 0,
			envelopeSustain: 0,
			envelopeRelease: 0.12,
			envelopePunch: 0.98,
			frequencyRamp: 0.038,
			frequencyDeltaRamp: -13,
		},
	},
	{
		name: 'Ride Cymbal 1',
		volume: 0.95,
		parameters: {
			envelopeAttack: 0,
			envelopeSustain: 0,
			envelopeRelease: 2.4,
			envelopePunch: 1.05,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
		},
	},
	{
		name: 'Chinese Cymbal',
		volume: 1,
		parameters: {
			envelopeAttack: 0,
			envelopeSustain: 0,
			envelopeRelease: 1.6,
			envelopePunch: 1.2,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
		},
	},
	{
		name: 'Ride Bell',
		volume: 0.95,
		parameters: {
			envelopeAttack: 0,
			envelopeSustain: 0,
			envelopeRelease: 1.3,
			envelopePunch: 1.1,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
		},
	},
	{
		name: 'Tambourine',
		volume: 0.9,
		parameters: {
			envelopeAttack: 0,
			envelopeSustain: 0.01,
			envelopeRelease: 0.7,
			envelopePunch: 1.15,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
		},
	},
	{
		name: 'Splash Cymbal',
		volume: 0.92,
		parameters: {
			envelopeAttack: 0,
			envelopeSustain: 0,
			envelopeRelease: 0.85,
			envelopePunch: 1.1,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
		},
	},
	{
		name: 'Cowbell',
		volume: 0.92,
		parameters: {
			envelopeAttack: 0,
			envelopeSustain: 0.02,
			envelopeRelease: 0.45,
			envelopePunch: 1,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
		},
	},
	{
		name: 'Crash Cymbal 2',
		volume: 0.98,
		parameters: {
			envelopeAttack: 0,
			envelopeSustain: 0,
			envelopeRelease: 1.9,
			envelopePunch: 1.15,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
		},
	},
	{
		name: 'Vibraslap',
		volume: 0.88,
		parameters: {
			envelopeAttack: 0,
			envelopeSustain: 0.03,
			envelopeRelease: 0.65,
			envelopePunch: 1.2,
			frequencyRamp: 0.02,
			frequencyDeltaRamp: -4,
		},
	},
	{
		name: 'Ride Cymbal 2',
		volume: 0.9,
		parameters: {
			envelopeAttack: 0,
			envelopeSustain: 0,
			envelopeRelease: 2.1,
			envelopePunch: 1,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
		},
	},
	{
		name: 'Hi Bongo',
		volume: 0.88,
		parameters: {
			envelopeAttack: 0,
			envelopeSustain: 0,
			envelopeRelease: 0.13,
			envelopePunch: 1.05,
			frequencyRamp: 0.025,
			frequencyDeltaRamp: -8,
		},
	},
	{
		name: 'Low Bongo',
		volume: 0.9,
		parameters: {
			envelopeAttack: 0,
			envelopeSustain: 0,
			envelopeRelease: 0.16,
			envelopePunch: 1.05,
			frequencyRamp: 0.03,
			frequencyDeltaRamp: -9,
		},
	},
	{
		name: 'Mute Hi Conga',
		volume: 0.88,
		parameters: {
			envelopeAttack: 0,
			envelopeSustain: 0,
			envelopeRelease: 0.1,
			envelopePunch: 0.95,
			frequencyRamp: 0.02,
			frequencyDeltaRamp: -6,
		},
	},
	{
		name: 'Open Hi Conga',
		volume: 0.9,
		parameters: {
			envelopeAttack: 0,
			envelopeSustain: 0.02,
			envelopeRelease: 0.26,
			envelopePunch: 1,
			frequencyRamp: 0.03,
			frequencyDeltaRamp: -8,
		},
	},
	{
		name: 'Low Conga',
		volume: 0.92,
		parameters: {
			envelopeAttack: 0,
			envelopeSustain: 0.02,
			envelopeRelease: 0.3,
			envelopePunch: 1,
			frequencyRamp: 0.04,
			frequencyDeltaRamp: -10,
		},
	},
	{
		name: 'High Timbale',
		volume: 0.92,
		parameters: {
			envelopeAttack: 0,
			envelopeSustain: 0,
			envelopeRelease: 0.12,
			envelopePunch: 1.05,
			frequencyRamp: 0.025,
			frequencyDeltaRamp: -12,
		},
	},
	{
		name: 'Low Timbale',
		volume: 0.94,
		parameters: {
			envelopeAttack: 0,
			envelopeSustain: 0,
			envelopeRelease: 0.15,
			envelopePunch: 1.05,
			frequencyRamp: 0.03,
			frequencyDeltaRamp: -14,
		},
	},
	{
		name: 'High Agogo',
		volume: 0.9,
		parameters: {
			envelopeAttack: 0,
			envelopeSustain: 0.01,
			envelopeRelease: 0.55,
			envelopePunch: 1.05,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
		},
	},
	{
		name: 'Low Agogo',
		volume: 0.9,
		parameters: {
			envelopeAttack: 0,
			envelopeSustain: 0.01,
			envelopeRelease: 0.65,
			envelopePunch: 1.05,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
		},
	},
	{
		name: 'Cabasa',
		volume: 0.85,
		parameters: {
			envelopeAttack: 0,
			envelopeSustain: 0.03,
			envelopeRelease: 0.3,
			envelopePunch: 1.1,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
		},
	},
	{
		name: 'Maracas',
		volume: 0.88,
		parameters: {
			envelopeAttack: 0,
			envelopeSustain: 0.02,
			envelopeRelease: 0.18,
			envelopePunch: 1.15,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
		},
	},
	{
		name: 'Short Whistle',
		volume: 0.82,
		parameters: {
			envelopeAttack: 0,
			envelopeSustain: 0.04,
			envelopeRelease: 0.18,
			envelopePunch: 0.9,
			frequencyRamp: 0.02,
			frequencyDeltaRamp: -2,
		},
	},
	{
		name: 'Long Whistle',
		volume: 0.84,
		parameters: {
			envelopeAttack: 0,
			envelopeSustain: 0.45,
			envelopeRelease: 0.3,
			envelopePunch: 0.8,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
		},
	},
	{
		name: 'Short Guiro',
		volume: 0.86,
		parameters: {
			envelopeAttack: 0,
			envelopeSustain: 0.03,
			envelopeRelease: 0.12,
			envelopePunch: 1.2,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
		},
	},
	{
		name: 'Long Guiro',
		volume: 0.86,
		parameters: {
			envelopeAttack: 0,
			envelopeSustain: 0.28,
			envelopeRelease: 0.22,
			envelopePunch: 1,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
		},
	},
	{
		name: 'Claves',
		volume: 0.92,
		parameters: {
			envelopeAttack: 0,
			envelopeSustain: 0,
			envelopeRelease: 0.08,
			envelopePunch: 1.1,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
		},
	},
	{
		name: 'Hi Wood Block',
		volume: 0.88,
		parameters: {
			envelopeAttack: 0,
			envelopeSustain: 0,
			envelopeRelease: 0.09,
			envelopePunch: 1,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
		},
	},
	{
		name: 'Low Wood Block',
		volume: 0.88,
		parameters: {
			envelopeAttack: 0,
			envelopeSustain: 0,
			envelopeRelease: 0.11,
			envelopePunch: 1,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
		},
	},
	{
		name: 'Mute Cuica',
		volume: 0.9,
		parameters: {
			envelopeAttack: 0,
			envelopeSustain: 0.05,
			envelopeRelease: 0.15,
			envelopePunch: 1.05,
			frequencyRamp: 0.06,
			frequencyDeltaRamp: 6,
		},
	},
	{
		name: 'Open Cuica',
		volume: 0.92,
		parameters: {
			envelopeAttack: 0,
			envelopeSustain: 0.12,
			envelopeRelease: 0.28,
			envelopePunch: 1,
			frequencyRamp: 0.1,
			frequencyDeltaRamp: 10,
		},
	},
	{
		name: 'Mute Triangle',
		volume: 0.82,
		parameters: {
			envelopeAttack: 0,
			envelopeSustain: 0.02,
			envelopeRelease: 0.7,
			envelopePunch: 0.95,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
		},
	},
	{
		name: 'Open Triangle',
		volume: 0.84,
		parameters: {
			envelopeAttack: 0,
			envelopeSustain: 0.05,
			envelopeRelease: 3.2,
			envelopePunch: 0.95,
			frequencyRamp: 0,
			frequencyDeltaRamp: 0,
		},
	},
];

export function get_instrument(index: number, isDrums: true): Drum | undefined;
export function get_instrument(
	index: number,
	isDrums: false,
): Instrument | undefined;
export function get_instrument(
	index: number,
	isDrums: boolean,
): Instrument | Drum | undefined {
	return isDrums ? percussion_map[index - 35] : instrument_map[index];
}
