const instrument_map = [
	{
		name: 'Acoustic Grand Piano',
		wave: 'sine',
		velocity: 0.7,
		attack: 0.003,
		sustain: 0.05,
		sustainPunch: 0.9,
		decay: 0.45,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Bright Acoustic Piano',
		wave: 'sine',
		velocity: 0.7,
		attack: 0.003,
		sustain: 0.05,
		sustainPunch: 0.9,
		decay: 0.45,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Electric Grand Piano',
		wave: 'sine',
		velocity: 0.7,
		attack: 0.003,
		sustain: 0.05,
		sustainPunch: 0.9,
		decay: 0.45,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Honky-tonk Piano',
		wave: 'sine',
		velocity: 0.7,
		attack: 0.003,
		sustain: 0.05,
		sustainPunch: 0.9,
		decay: 0.45,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Electric Piano 1',
		wave: 'sine',
		velocity: 0.7,
		attack: 0.003,
		sustain: 0.05,
		sustainPunch: 0.9,
		decay: 0.45,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Electric Piano 2',
		wave: 'sine',
		velocity: 0.7,
		attack: 0.003,
		sustain: 0.05,
		sustainPunch: 0.9,
		decay: 0.45,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Harpsichord',
		wave: 'square',
		velocity: 0.8,
		attack: 0.01,
		sustain: 0.25,
		sustainPunch: 0.3,
		decay: 0.25,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Clavinet',
		wave: 'square',
		velocity: 0.8,
		attack: 0.01,
		sustain: 0.25,
		sustainPunch: 0.3,
		decay: 0.25,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Celesta',
		wave: 'sine',
		velocity: 0.7,
		attack: 0.001,
		sustain: 0.0,
		sustainPunch: 1.2,
		decay: 2.5,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Glockenspiel',
		wave: 'sine',
		velocity: 0.7,
		attack: 0.001,
		sustain: 0.0,
		sustainPunch: 1.2,
		decay: 2.5,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Music Box',
		wave: 'sine',
		velocity: 0.7,
		attack: 0.01,
		sustain: 0.25,
		sustainPunch: 0.3,
		decay: 0.25,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Vibraphone',
		wave: 'sine',
		velocity: 0.7,
		attack: 0.001,
		sustain: 0.0,
		sustainPunch: 1.2,
		decay: 2.5,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Marimba',
		wave: 'sine',
		velocity: 0.7,
		attack: 0.01,
		sustain: 0.25,
		sustainPunch: 0.3,
		decay: 0.25,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Xylophone',
		wave: 'sine',
		velocity: 0.7,
		attack: 0.01,
		sustain: 0.25,
		sustainPunch: 0.3,
		decay: 0.25,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Tubular Bells',
		wave: 'sine',
		velocity: 0.7,
		attack: 0.001,
		sustain: 0.0,
		sustainPunch: 1.2,
		decay: 2.5,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Dulcimer',
		wave: 'sine',
		velocity: 0.7,
		attack: 0.01,
		sustain: 0.25,
		sustainPunch: 0.3,
		decay: 0.25,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Drawbar Organ',
		wave: 'square',
		velocity: 0.8,
		attack: 0.005,
		sustain: 2.0,
		sustainPunch: 0.0,
		decay: 0.05,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Percussive Organ',
		wave: 'square',
		velocity: 0.8,
		attack: 0.005,
		sustain: 2.0,
		sustainPunch: 0.0,
		decay: 0.05,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Rock Organ',
		wave: 'square',
		velocity: 0.8,
		attack: 0.005,
		sustain: 2.0,
		sustainPunch: 0.0,
		decay: 0.05,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Church Organ',
		wave: 'square',
		velocity: 0.8,
		attack: 0.005,
		sustain: 2.0,
		sustainPunch: 0.0,
		decay: 0.05,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Reed Organ',
		wave: 'square',
		velocity: 0.8,
		attack: 0.005,
		sustain: 2.0,
		sustainPunch: 0.0,
		decay: 0.05,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Accordion',
		wave: 'square',
		velocity: 0.8,
		attack: 0.01,
		sustain: 0.25,
		sustainPunch: 0.3,
		decay: 0.25,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Harmonica',
		wave: 'square',
		velocity: 0.8,
		attack: 0.01,
		sustain: 0.25,
		sustainPunch: 0.3,
		decay: 0.25,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Tango Accordion',
		wave: 'square',
		velocity: 0.8,
		attack: 0.01,
		sustain: 0.25,
		sustainPunch: 0.3,
		decay: 0.25,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Acoustic Guitar (nylon)',
		wave: 'sawtooth',
		velocity: 0.85,
		attack: 0.005,
		sustain: 0.06,
		sustainPunch: 0.8,
		decay: 0.3,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Acoustic Guitar (steel)',
		wave: 'sawtooth',
		velocity: 0.85,
		attack: 0.005,
		sustain: 0.06,
		sustainPunch: 0.8,
		decay: 0.3,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Electric Guitar (jazz)',
		wave: 'sawtooth',
		velocity: 0.85,
		attack: 0.005,
		sustain: 0.06,
		sustainPunch: 0.8,
		decay: 0.3,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Electric Guitar (clean)',
		wave: 'sawtooth',
		velocity: 0.85,
		attack: 0.005,
		sustain: 0.06,
		sustainPunch: 0.8,
		decay: 0.3,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Electric Guitar (muted)',
		wave: 'sawtooth',
		velocity: 0.85,
		attack: 0.005,
		sustain: 0.06,
		sustainPunch: 0.8,
		decay: 0.3,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Overdriven Guitar',
		wave: 'sawtooth',
		velocity: 0.85,
		attack: 0.005,
		sustain: 0.06,
		sustainPunch: 0.8,
		decay: 0.3,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Distortion Guitar',
		wave: 'sawtooth',
		velocity: 0.85,
		attack: 0.005,
		sustain: 0.06,
		sustainPunch: 0.8,
		decay: 0.3,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Guitar Harmonics',
		wave: 'sawtooth',
		velocity: 0.85,
		attack: 0.005,
		sustain: 0.06,
		sustainPunch: 0.8,
		decay: 0.3,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Acoustic Bass',
		wave: 'sawtooth',
		velocity: 0.85,
		attack: 0.005,
		sustain: 0.06,
		sustainPunch: 0.8,
		decay: 0.3,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Electric Bass (finger)',
		wave: 'sawtooth',
		velocity: 0.85,
		attack: 0.005,
		sustain: 0.06,
		sustainPunch: 0.8,
		decay: 0.3,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Electric Bass (pick)',
		wave: 'sawtooth',
		velocity: 0.85,
		attack: 0.005,
		sustain: 0.06,
		sustainPunch: 0.8,
		decay: 0.3,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Fretless Bass',
		wave: 'sawtooth',
		velocity: 0.85,
		attack: 0.005,
		sustain: 0.06,
		sustainPunch: 0.8,
		decay: 0.3,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Slap Bass 1',
		wave: 'sawtooth',
		velocity: 0.85,
		attack: 0.005,
		sustain: 0.06,
		sustainPunch: 0.8,
		decay: 0.3,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Slap Bass 2',
		wave: 'sawtooth',
		velocity: 0.85,
		attack: 0.005,
		sustain: 0.06,
		sustainPunch: 0.8,
		decay: 0.3,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Synth Bass 1',
		wave: 'sawtooth',
		velocity: 0.85,
		attack: 0.005,
		sustain: 0.06,
		sustainPunch: 0.8,
		decay: 0.3,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Synth Bass 2',
		wave: 'sawtooth',
		velocity: 0.85,
		attack: 0.005,
		sustain: 0.06,
		sustainPunch: 0.8,
		decay: 0.3,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Violin',
		wave: 'sawtooth',
		velocity: 0.85,
		attack: 0.1,
		sustain: 1.2,
		sustainPunch: 0.1,
		decay: 0.35,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0.02,
		vibratoRate: 5.5,
	},
	{
		name: 'Viola',
		wave: 'sawtooth',
		velocity: 0.85,
		attack: 0.1,
		sustain: 1.2,
		sustainPunch: 0.1,
		decay: 0.35,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0.02,
		vibratoRate: 5.5,
	},
	{
		name: 'Cello',
		wave: 'sawtooth',
		velocity: 0.85,
		attack: 0.1,
		sustain: 1.2,
		sustainPunch: 0.1,
		decay: 0.35,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0.02,
		vibratoRate: 5.5,
	},
	{
		name: 'Contrabass',
		wave: 'sawtooth',
		velocity: 0.85,
		attack: 0.1,
		sustain: 1.2,
		sustainPunch: 0.1,
		decay: 0.35,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Tremolo Strings',
		wave: 'sawtooth',
		velocity: 0.85,
		attack: 0.1,
		sustain: 1.2,
		sustainPunch: 0.1,
		decay: 0.35,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Pizzicato Strings',
		wave: 'sawtooth',
		velocity: 0.85,
		attack: 0.1,
		sustain: 1.2,
		sustainPunch: 0.1,
		decay: 0.35,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Orchestral Harp',
		wave: 'sawtooth',
		velocity: 0.85,
		attack: 0.01,
		sustain: 0.25,
		sustainPunch: 0.3,
		decay: 0.25,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Timpani',
		wave: 'noise',
		velocity: 0.9,
		attack: 0.001,
		sustain: 0.0,
		sustainPunch: 1.0,
		decay: 0.08,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'String Ensemble 1',
		wave: 'sawtooth',
		velocity: 0.85,
		attack: 0.1,
		sustain: 1.2,
		sustainPunch: 0.1,
		decay: 0.35,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'String Ensemble 2',
		wave: 'sawtooth',
		velocity: 0.85,
		attack: 0.1,
		sustain: 1.2,
		sustainPunch: 0.1,
		decay: 0.35,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Synth Strings 1',
		wave: 'sawtooth',
		velocity: 0.85,
		attack: 0.1,
		sustain: 1.2,
		sustainPunch: 0.1,
		decay: 0.35,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Synth Strings 2',
		wave: 'sawtooth',
		velocity: 0.85,
		attack: 0.1,
		sustain: 1.2,
		sustainPunch: 0.1,
		decay: 0.35,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Choir Aahs',
		wave: 'sine',
		velocity: 0.7,
		attack: 0.01,
		sustain: 0.25,
		sustainPunch: 0.3,
		decay: 0.25,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Voice Oohs',
		wave: 'sine',
		velocity: 0.7,
		attack: 0.01,
		sustain: 0.25,
		sustainPunch: 0.3,
		decay: 0.25,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Synth Choir',
		wave: 'sine',
		velocity: 0.7,
		attack: 0.01,
		sustain: 0.25,
		sustainPunch: 0.3,
		decay: 0.25,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Orchestra Hit',
		wave: 'sawtooth',
		velocity: 0.85,
		attack: 0.01,
		sustain: 0.25,
		sustainPunch: 0.3,
		decay: 0.25,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Trumpet',
		wave: 'sawtooth',
		velocity: 0.85,
		attack: 0.04,
		sustain: 0.8,
		sustainPunch: 0.4,
		decay: 0.2,
		freqRamp: 0.05,
		freqDeltaRamp: 0.3,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Trombone',
		wave: 'sawtooth',
		velocity: 0.85,
		attack: 0.04,
		sustain: 0.8,
		sustainPunch: 0.4,
		decay: 0.2,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Tuba',
		wave: 'sawtooth',
		velocity: 0.85,
		attack: 0.04,
		sustain: 0.8,
		sustainPunch: 0.4,
		decay: 0.2,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Muted Trumpet',
		wave: 'square',
		velocity: 0.8,
		attack: 0.04,
		sustain: 0.8,
		sustainPunch: 0.4,
		decay: 0.2,
		freqRamp: 0.05,
		freqDeltaRamp: 0.3,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'French Horn',
		wave: 'sawtooth',
		velocity: 0.85,
		attack: 0.04,
		sustain: 0.8,
		sustainPunch: 0.4,
		decay: 0.2,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Brass Section',
		wave: 'sawtooth',
		velocity: 0.85,
		attack: 0.04,
		sustain: 0.8,
		sustainPunch: 0.4,
		decay: 0.2,
		freqRamp: 0.05,
		freqDeltaRamp: 0.3,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Synth Brass 1',
		wave: 'sawtooth',
		velocity: 0.85,
		attack: 0.04,
		sustain: 0.8,
		sustainPunch: 0.4,
		decay: 0.2,
		freqRamp: 0.05,
		freqDeltaRamp: 0.3,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Synth Brass 2',
		wave: 'square',
		velocity: 0.8,
		attack: 0.04,
		sustain: 0.8,
		sustainPunch: 0.4,
		decay: 0.2,
		freqRamp: 0.05,
		freqDeltaRamp: 0.3,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Soprano Sax',
		wave: 'square',
		velocity: 0.8,
		attack: 0.01,
		sustain: 0.25,
		sustainPunch: 0.3,
		decay: 0.25,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0.02,
		vibratoRate: 5.5,
	},
	{
		name: 'Alto Sax',
		wave: 'square',
		velocity: 0.8,
		attack: 0.01,
		sustain: 0.25,
		sustainPunch: 0.3,
		decay: 0.25,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0.02,
		vibratoRate: 5.5,
	},
	{
		name: 'Tenor Sax',
		wave: 'square',
		velocity: 0.8,
		attack: 0.01,
		sustain: 0.25,
		sustainPunch: 0.3,
		decay: 0.25,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0.02,
		vibratoRate: 5.5,
	},
	{
		name: 'Baritone Sax',
		wave: 'square',
		velocity: 0.8,
		attack: 0.01,
		sustain: 0.25,
		sustainPunch: 0.3,
		decay: 0.25,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0.02,
		vibratoRate: 5.5,
	},
	{
		name: 'Oboe',
		wave: 'square',
		velocity: 0.8,
		attack: 0.01,
		sustain: 0.25,
		sustainPunch: 0.3,
		decay: 0.25,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'English Horn',
		wave: 'square',
		velocity: 0.8,
		attack: 0.04,
		sustain: 0.8,
		sustainPunch: 0.4,
		decay: 0.2,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Bassoon',
		wave: 'square',
		velocity: 0.8,
		attack: 0.005,
		sustain: 0.06,
		sustainPunch: 0.8,
		decay: 0.3,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Clarinet',
		wave: 'square',
		velocity: 0.8,
		attack: 0.01,
		sustain: 0.25,
		sustainPunch: 0.3,
		decay: 0.25,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Piccolo',
		wave: 'sine',
		velocity: 0.7,
		attack: 0.03,
		sustain: 1.0,
		sustainPunch: 0.05,
		decay: 0.2,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Flute',
		wave: 'sine',
		velocity: 0.7,
		attack: 0.03,
		sustain: 1.0,
		sustainPunch: 0.05,
		decay: 0.2,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0.02,
		vibratoRate: 5.5,
	},
	{
		name: 'Recorder',
		wave: 'sine',
		velocity: 0.7,
		attack: 0.03,
		sustain: 1.0,
		sustainPunch: 0.05,
		decay: 0.2,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Pan Flute',
		wave: 'sine',
		velocity: 0.7,
		attack: 0.03,
		sustain: 1.0,
		sustainPunch: 0.05,
		decay: 0.2,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0.02,
		vibratoRate: 5.5,
	},
	{
		name: 'Blown Bottle',
		wave: 'sine',
		velocity: 0.7,
		attack: 0.01,
		sustain: 0.25,
		sustainPunch: 0.3,
		decay: 0.25,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Shakuhachi',
		wave: 'sine',
		velocity: 0.7,
		attack: 0.03,
		sustain: 1.0,
		sustainPunch: 0.05,
		decay: 0.2,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Whistle',
		wave: 'sine',
		velocity: 0.7,
		attack: 0.03,
		sustain: 1.0,
		sustainPunch: 0.05,
		decay: 0.2,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Ocarina',
		wave: 'sine',
		velocity: 0.7,
		attack: 0.03,
		sustain: 1.0,
		sustainPunch: 0.05,
		decay: 0.2,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Lead 1 (square)',
		wave: 'square',
		velocity: 0.8,
		attack: 0.01,
		sustain: 0.25,
		sustainPunch: 0.3,
		decay: 0.25,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Lead 2 (sawtooth)',
		wave: 'sawtooth',
		velocity: 0.85,
		attack: 0.01,
		sustain: 0.25,
		sustainPunch: 0.3,
		decay: 0.25,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Lead 3 (calliope)',
		wave: 'square',
		velocity: 0.8,
		attack: 0.01,
		sustain: 0.25,
		sustainPunch: 0.3,
		decay: 0.25,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Lead 4 (chiff)',
		wave: 'square',
		velocity: 0.8,
		attack: 0.01,
		sustain: 0.25,
		sustainPunch: 0.3,
		decay: 0.25,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Lead 5 (charang)',
		wave: 'sawtooth',
		velocity: 0.85,
		attack: 0.01,
		sustain: 0.25,
		sustainPunch: 0.3,
		decay: 0.25,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Lead 6 (voice)',
		wave: 'sine',
		velocity: 0.7,
		attack: 0.01,
		sustain: 0.25,
		sustainPunch: 0.3,
		decay: 0.25,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Lead 7 (fifths)',
		wave: 'sawtooth',
		velocity: 0.85,
		attack: 0.01,
		sustain: 0.25,
		sustainPunch: 0.3,
		decay: 0.25,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Lead 8 (bass+lead)',
		wave: 'sawtooth',
		velocity: 0.85,
		attack: 0.01,
		sustain: 0.25,
		sustainPunch: 0.3,
		decay: 0.25,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Pad 1 (new age)',
		wave: 'sawtooth',
		velocity: 0.85,
		attack: 0.5,
		sustain: 2.5,
		sustainPunch: 0.0,
		decay: 0.8,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Pad 2 (warm)',
		wave: 'sawtooth',
		velocity: 0.85,
		attack: 0.5,
		sustain: 2.5,
		sustainPunch: 0.0,
		decay: 0.8,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Pad 3 (polysynth)',
		wave: 'sawtooth',
		velocity: 0.85,
		attack: 0.5,
		sustain: 2.5,
		sustainPunch: 0.0,
		decay: 0.8,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Pad 4 (choir)',
		wave: 'sawtooth',
		velocity: 0.85,
		attack: 0.5,
		sustain: 2.5,
		sustainPunch: 0.0,
		decay: 0.8,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Pad 5 (bowed)',
		wave: 'sawtooth',
		velocity: 0.85,
		attack: 0.5,
		sustain: 2.5,
		sustainPunch: 0.0,
		decay: 0.8,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Pad 6 (metallic)',
		wave: 'sawtooth',
		velocity: 0.85,
		attack: 0.5,
		sustain: 2.5,
		sustainPunch: 0.0,
		decay: 0.8,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Pad 7 (halo)',
		wave: 'sawtooth',
		velocity: 0.85,
		attack: 0.5,
		sustain: 2.5,
		sustainPunch: 0.0,
		decay: 0.8,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Pad 8 (sweep)',
		wave: 'sawtooth',
		velocity: 0.85,
		attack: 0.5,
		sustain: 2.5,
		sustainPunch: 0.0,
		decay: 0.8,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'FX 1 (rain)',
		wave: 'noise',
		velocity: 0.9,
		attack: 0.01,
		sustain: 0.25,
		sustainPunch: 0.3,
		decay: 0.25,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'FX 2 (soundtrack)',
		wave: 'sawtooth',
		velocity: 0.85,
		attack: 0.01,
		sustain: 0.25,
		sustainPunch: 0.3,
		decay: 0.25,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'FX 3 (crystal)',
		wave: 'sine',
		velocity: 0.7,
		attack: 0.01,
		sustain: 0.25,
		sustainPunch: 0.3,
		decay: 0.25,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'FX 4 (atmosphere)',
		wave: 'noise',
		velocity: 0.9,
		attack: 0.01,
		sustain: 0.25,
		sustainPunch: 0.3,
		decay: 0.25,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'FX 5 (brightness)',
		wave: 'sawtooth',
		velocity: 0.85,
		attack: 0.01,
		sustain: 0.25,
		sustainPunch: 0.3,
		decay: 0.25,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'FX 6 (goblins)',
		wave: 'noise',
		velocity: 0.9,
		attack: 0.01,
		sustain: 0.25,
		sustainPunch: 0.3,
		decay: 0.25,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'FX 7 (echoes)',
		wave: 'sine',
		velocity: 0.7,
		attack: 0.01,
		sustain: 0.25,
		sustainPunch: 0.3,
		decay: 0.25,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'FX 8 (sci-fi)',
		wave: 'sawtooth',
		velocity: 0.85,
		attack: 0.01,
		sustain: 0.25,
		sustainPunch: 0.3,
		decay: 0.25,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Sitar',
		wave: 'sawtooth',
		velocity: 0.85,
		attack: 0.01,
		sustain: 0.25,
		sustainPunch: 0.3,
		decay: 0.25,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Banjo',
		wave: 'square',
		velocity: 0.8,
		attack: 0.01,
		sustain: 0.25,
		sustainPunch: 0.3,
		decay: 0.25,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Shamisen',
		wave: 'square',
		velocity: 0.8,
		attack: 0.01,
		sustain: 0.25,
		sustainPunch: 0.3,
		decay: 0.25,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Koto',
		wave: 'sine',
		velocity: 0.7,
		attack: 0.01,
		sustain: 0.25,
		sustainPunch: 0.3,
		decay: 0.25,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Kalimba',
		wave: 'sine',
		velocity: 0.7,
		attack: 0.01,
		sustain: 0.25,
		sustainPunch: 0.3,
		decay: 0.25,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Bagpipe',
		wave: 'square',
		velocity: 0.8,
		attack: 0.01,
		sustain: 0.25,
		sustainPunch: 0.3,
		decay: 0.25,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Fiddle',
		wave: 'sawtooth',
		velocity: 0.85,
		attack: 0.01,
		sustain: 0.25,
		sustainPunch: 0.3,
		decay: 0.25,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Shanai',
		wave: 'square',
		velocity: 0.8,
		attack: 0.01,
		sustain: 0.25,
		sustainPunch: 0.3,
		decay: 0.25,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Tinkle Bell',
		wave: 'sine',
		velocity: 0.7,
		attack: 0.001,
		sustain: 0.0,
		sustainPunch: 1.2,
		decay: 2.5,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Agogo',
		wave: 'noise',
		velocity: 0.9,
		attack: 0.01,
		sustain: 0.25,
		sustainPunch: 0.3,
		decay: 0.25,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Steel Drums',
		wave: 'sine',
		velocity: 0.7,
		attack: 0.001,
		sustain: 0.0,
		sustainPunch: 1.0,
		decay: 0.08,
		freqRamp: 0.05,
		freqDeltaRamp: -18,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Woodblock',
		wave: 'noise',
		velocity: 0.9,
		attack: 0.01,
		sustain: 0.25,
		sustainPunch: 0.3,
		decay: 0.25,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Taiko Drum',
		wave: 'noise',
		velocity: 0.9,
		attack: 0.001,
		sustain: 0.0,
		sustainPunch: 1.0,
		decay: 0.08,
		freqRamp: 0.05,
		freqDeltaRamp: -18,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Melodic Tom',
		wave: 'noise',
		velocity: 0.9,
		attack: 0.001,
		sustain: 0.0,
		sustainPunch: 1.0,
		decay: 0.08,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Synth Drum',
		wave: 'noise',
		velocity: 0.9,
		attack: 0.001,
		sustain: 0.0,
		sustainPunch: 1.0,
		decay: 0.08,
		freqRamp: 0.05,
		freqDeltaRamp: -18,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Reverse Cymbal',
		wave: 'noise',
		velocity: 0.9,
		attack: 0.01,
		sustain: 0.25,
		sustainPunch: 0.3,
		decay: 0.25,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Guitar Fret Noise',
		wave: 'noise',
		velocity: 0.9,
		attack: 0.005,
		sustain: 0.06,
		sustainPunch: 0.8,
		decay: 0.3,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Breath Noise',
		wave: 'noise',
		velocity: 0.9,
		attack: 0.01,
		sustain: 0.25,
		sustainPunch: 0.3,
		decay: 0.25,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Seashore',
		wave: 'noise',
		velocity: 0.9,
		attack: 0.01,
		sustain: 0.25,
		sustainPunch: 0.3,
		decay: 0.25,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Bird Tweet',
		wave: 'sine',
		velocity: 0.7,
		attack: 0.01,
		sustain: 0.25,
		sustainPunch: 0.3,
		decay: 0.25,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Telephone Ring',
		wave: 'square',
		velocity: 0.8,
		attack: 0.01,
		sustain: 0.25,
		sustainPunch: 0.3,
		decay: 0.25,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Helicopter',
		wave: 'noise',
		velocity: 0.9,
		attack: 0.001,
		sustain: 0.0,
		sustainPunch: 1.0,
		decay: 0.08,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Applause',
		wave: 'noise',
		velocity: 0.9,
		attack: 0.001,
		sustain: 0.0,
		sustainPunch: 1.0,
		decay: 0.08,
		freqRamp: 0,
		freqDeltaRamp: 0,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
	{
		name: 'Gunshot',
		wave: 'noise',
		velocity: 0.9,
		attack: 0.001,
		sustain: 0.0,
		sustainPunch: 1.0,
		decay: 0.08,
		freqRamp: 0.05,
		freqDeltaRamp: -18,
		vibratoDepth: 0,
		vibratoRate: 0,
	},
];

const percussion_map = [
	{
		name: 'Acoustic Bass Drum',
		basePitch: 44,
		velocity: 1.0,
		attack: 0.0,
		sustain: 0.0,
		sustainPunch: 1.2,
		decay: 0.22,
		freqRamp: 0.06,
		freqDeltaRamp: -28,
	},
	{
		name: 'Bass Drum 1',
		basePitch: 46,
		velocity: 1.0,
		attack: 0.0,
		sustain: 0.0,
		sustainPunch: 1.15,
		decay: 0.2,
		freqRamp: 0.05,
		freqDeltaRamp: -24,
	},
	{
		name: 'Side Stick',
		basePitch: 82,
		velocity: 0.85,
		attack: 0.0,
		sustain: 0.0,
		sustainPunch: 0.95,
		decay: 0.035,
		freqRamp: 0.0,
		freqDeltaRamp: 0,
	},
	{
		name: 'Acoustic Snare',
		basePitch: 64,
		velocity: 0.98,
		attack: 0.0,
		sustain: 0.0,
		sustainPunch: 1.1,
		decay: 0.12,
		freqRamp: 0.035,
		freqDeltaRamp: -12,
	},
	{
		name: 'Hand Clap',
		basePitch: 72,
		velocity: 0.92,
		attack: 0.0,
		sustain: 0.02,
		sustainPunch: 1.25,
		decay: 0.16,
		freqRamp: 0.0,
		freqDeltaRamp: 0,
	},
	{
		name: 'Electric Snare',
		basePitch: 67,
		velocity: 0.95,
		attack: 0.0,
		sustain: 0.0,
		sustainPunch: 1.05,
		decay: 0.1,
		freqRamp: 0.03,
		freqDeltaRamp: -10,
	},
	{
		name: 'Low Floor Tom',
		basePitch: 42,
		velocity: 0.96,
		attack: 0.0,
		sustain: 0.0,
		sustainPunch: 1.0,
		decay: 0.18,
		freqRamp: 0.05,
		freqDeltaRamp: -18,
	},
	{
		name: 'Closed Hi-Hat',
		basePitch: 98,
		velocity: 0.88,
		attack: 0.0,
		sustain: 0.0,
		sustainPunch: 1.05,
		decay: 0.045,
		freqRamp: 0.0,
		freqDeltaRamp: 0,
	},
	{
		name: 'High Floor Tom',
		basePitch: 47,
		velocity: 0.95,
		attack: 0.0,
		sustain: 0.0,
		sustainPunch: 1.0,
		decay: 0.16,
		freqRamp: 0.048,
		freqDeltaRamp: -17,
	},
	{
		name: 'Pedal Hi-Hat',
		basePitch: 95,
		velocity: 0.82,
		attack: 0.0,
		sustain: 0.0,
		sustainPunch: 0.95,
		decay: 0.035,
		freqRamp: 0.0,
		freqDeltaRamp: 0,
	},
	{
		name: 'Low Tom',
		basePitch: 50,
		velocity: 0.94,
		attack: 0.0,
		sustain: 0.0,
		sustainPunch: 1.0,
		decay: 0.15,
		freqRamp: 0.045,
		freqDeltaRamp: -16,
	},
	{
		name: 'Open Hi-Hat',
		basePitch: 100,
		velocity: 0.92,
		attack: 0.0,
		sustain: 0.0,
		sustainPunch: 1.1,
		decay: 0.42,
		freqRamp: 0.0,
		freqDeltaRamp: 0,
	},
	{
		name: 'Low-Mid Tom',
		basePitch: 53,
		velocity: 0.93,
		attack: 0.0,
		sustain: 0.0,
		sustainPunch: 1.0,
		decay: 0.14,
		freqRamp: 0.042,
		freqDeltaRamp: -15,
	},
	{
		name: 'Hi-Mid Tom',
		basePitch: 57,
		velocity: 0.92,
		attack: 0.0,
		sustain: 0.0,
		sustainPunch: 1.0,
		decay: 0.13,
		freqRamp: 0.04,
		freqDeltaRamp: -14,
	},
	{
		name: 'Crash Cymbal 1',
		basePitch: 110,
		velocity: 1.0,
		attack: 0.0,
		sustain: 0.0,
		sustainPunch: 1.15,
		decay: 1.8,
		freqRamp: 0.0,
		freqDeltaRamp: 0,
	},
	{
		name: 'High Tom',
		basePitch: 60,
		velocity: 0.9,
		attack: 0.0,
		sustain: 0.0,
		sustainPunch: 0.98,
		decay: 0.12,
		freqRamp: 0.038,
		freqDeltaRamp: -13,
	},
	{
		name: 'Ride Cymbal 1',
		basePitch: 104,
		velocity: 0.95,
		attack: 0.0,
		sustain: 0.0,
		sustainPunch: 1.05,
		decay: 2.4,
		freqRamp: 0.0,
		freqDeltaRamp: 0,
	},
	{
		name: 'Chinese Cymbal',
		basePitch: 107,
		velocity: 1.0,
		attack: 0.0,
		sustain: 0.0,
		sustainPunch: 1.2,
		decay: 1.6,
		freqRamp: 0.0,
		freqDeltaRamp: 0,
	},
	{
		name: 'Ride Bell',
		basePitch: 111,
		velocity: 0.95,
		attack: 0.0,
		sustain: 0.0,
		sustainPunch: 1.1,
		decay: 1.3,
		freqRamp: 0.0,
		freqDeltaRamp: 0,
	},
	{
		name: 'Tambourine',
		basePitch: 90,
		velocity: 0.9,
		attack: 0.0,
		sustain: 0.01,
		sustainPunch: 1.15,
		decay: 0.7,
		freqRamp: 0.0,
		freqDeltaRamp: 0,
	},
	{
		name: 'Splash Cymbal',
		basePitch: 113,
		velocity: 0.92,
		attack: 0.0,
		sustain: 0.0,
		sustainPunch: 1.1,
		decay: 0.85,
		freqRamp: 0.0,
		freqDeltaRamp: 0,
	},
	{
		name: 'Cowbell',
		basePitch: 84,
		velocity: 0.92,
		attack: 0.0,
		sustain: 0.02,
		sustainPunch: 1.0,
		decay: 0.45,
		freqRamp: 0.0,
		freqDeltaRamp: 0,
	},
	{
		name: 'Crash Cymbal 2',
		basePitch: 109,
		velocity: 0.98,
		attack: 0.0,
		sustain: 0.0,
		sustainPunch: 1.15,
		decay: 1.9,
		freqRamp: 0.0,
		freqDeltaRamp: 0,
	},
	{
		name: 'Vibraslap',
		basePitch: 76,
		velocity: 0.88,
		attack: 0.0,
		sustain: 0.03,
		sustainPunch: 1.2,
		decay: 0.65,
		freqRamp: 0.02,
		freqDeltaRamp: -4,
	},
	{
		name: 'Ride Cymbal 2',
		basePitch: 102,
		velocity: 0.9,
		attack: 0.0,
		sustain: 0.0,
		sustainPunch: 1.0,
		decay: 2.1,
		freqRamp: 0.0,
		freqDeltaRamp: 0,
	},
	{
		name: 'Hi Bongo',
		basePitch: 76,
		velocity: 0.88,
		attack: 0.0,
		sustain: 0.0,
		sustainPunch: 1.05,
		decay: 0.13,
		freqRamp: 0.025,
		freqDeltaRamp: -8,
	},
	{
		name: 'Low Bongo',
		basePitch: 68,
		velocity: 0.9,
		attack: 0.0,
		sustain: 0.0,
		sustainPunch: 1.05,
		decay: 0.16,
		freqRamp: 0.03,
		freqDeltaRamp: -9,
	},
	{
		name: 'Mute Hi Conga',
		basePitch: 80,
		velocity: 0.88,
		attack: 0.0,
		sustain: 0.0,
		sustainPunch: 0.95,
		decay: 0.1,
		freqRamp: 0.02,
		freqDeltaRamp: -6,
	},
	{
		name: 'Open Hi Conga',
		basePitch: 82,
		velocity: 0.9,
		attack: 0.0,
		sustain: 0.02,
		sustainPunch: 1.0,
		decay: 0.26,
		freqRamp: 0.03,
		freqDeltaRamp: -8,
	},
	{
		name: 'Low Conga',
		basePitch: 62,
		velocity: 0.92,
		attack: 0.0,
		sustain: 0.02,
		sustainPunch: 1.0,
		decay: 0.3,
		freqRamp: 0.04,
		freqDeltaRamp: -10,
	},
	{
		name: 'High Timbale',
		basePitch: 84,
		velocity: 0.92,
		attack: 0.0,
		sustain: 0.0,
		sustainPunch: 1.05,
		decay: 0.12,
		freqRamp: 0.025,
		freqDeltaRamp: -12,
	},
	{
		name: 'Low Timbale',
		basePitch: 74,
		velocity: 0.94,
		attack: 0.0,
		sustain: 0.0,
		sustainPunch: 1.05,
		decay: 0.15,
		freqRamp: 0.03,
		freqDeltaRamp: -14,
	},
	{
		name: 'High Agogo',
		basePitch: 92,
		velocity: 0.9,
		attack: 0.0,
		sustain: 0.01,
		sustainPunch: 1.05,
		decay: 0.55,
		freqRamp: 0.0,
		freqDeltaRamp: 0,
	},
	{
		name: 'Low Agogo',
		basePitch: 80,
		velocity: 0.9,
		attack: 0.0,
		sustain: 0.01,
		sustainPunch: 1.05,
		decay: 0.65,
		freqRamp: 0.0,
		freqDeltaRamp: 0,
	},
	{
		name: 'Cabasa',
		basePitch: 90,
		velocity: 0.85,
		attack: 0.0,
		sustain: 0.03,
		sustainPunch: 1.1,
		decay: 0.3,
		freqRamp: 0.0,
		freqDeltaRamp: 0,
	},
	{
		name: 'Maracas',
		basePitch: 94,
		velocity: 0.88,
		attack: 0.0,
		sustain: 0.02,
		sustainPunch: 1.15,
		decay: 0.18,
		freqRamp: 0.0,
		freqDeltaRamp: 0,
	},
	{
		name: 'Short Whistle',
		basePitch: 106,
		velocity: 0.82,
		attack: 0.0,
		sustain: 0.04,
		sustainPunch: 0.9,
		decay: 0.18,
		freqRamp: 0.02,
		freqDeltaRamp: -2,
	},
	{
		name: 'Long Whistle',
		basePitch: 98,
		velocity: 0.84,
		attack: 0.0,
		sustain: 0.45,
		sustainPunch: 0.8,
		decay: 0.3,
		freqRamp: 0.0,
		freqDeltaRamp: 0,
	},
	{
		name: 'Short Guiro',
		basePitch: 88,
		velocity: 0.86,
		attack: 0.0,
		sustain: 0.03,
		sustainPunch: 1.2,
		decay: 0.12,
		freqRamp: 0.0,
		freqDeltaRamp: 0,
	},
	{
		name: 'Long Guiro',
		basePitch: 78,
		velocity: 0.86,
		attack: 0.0,
		sustain: 0.28,
		sustainPunch: 1.0,
		decay: 0.22,
		freqRamp: 0.0,
		freqDeltaRamp: 0,
	},
	{
		name: 'Claves',
		basePitch: 86,
		velocity: 0.92,
		attack: 0.0,
		sustain: 0.0,
		sustainPunch: 1.1,
		decay: 0.08,
		freqRamp: 0.0,
		freqDeltaRamp: 0,
	},
	{
		name: 'Hi Wood Block',
		basePitch: 95,
		velocity: 0.88,
		attack: 0.0,
		sustain: 0.0,
		sustainPunch: 1.0,
		decay: 0.09,
		freqRamp: 0.0,
		freqDeltaRamp: 0,
	},
	{
		name: 'Low Wood Block',
		basePitch: 82,
		velocity: 0.88,
		attack: 0.0,
		sustain: 0.0,
		sustainPunch: 1.0,
		decay: 0.11,
		freqRamp: 0.0,
		freqDeltaRamp: 0,
	},
	{
		name: 'Mute Cuica',
		basePitch: 74,
		velocity: 0.9,
		attack: 0.0,
		sustain: 0.05,
		sustainPunch: 1.05,
		decay: 0.15,
		freqRamp: 0.06,
		freqDeltaRamp: 6,
	},
	{
		name: 'Open Cuica',
		basePitch: 70,
		velocity: 0.92,
		attack: 0.0,
		sustain: 0.12,
		sustainPunch: 1.0,
		decay: 0.28,
		freqRamp: 0.1,
		freqDeltaRamp: 10,
	},
	{
		name: 'Mute Triangle',
		basePitch: 103,
		velocity: 0.82,
		attack: 0.0,
		sustain: 0.02,
		sustainPunch: 0.95,
		decay: 0.7,
		freqRamp: 0.0,
		freqDeltaRamp: 0,
	},
	{
		name: 'Open Triangle',
		basePitch: 105,
		velocity: 0.84,
		attack: 0.0,
		sustain: 0.05,
		sustainPunch: 0.95,
		decay: 3.2,
		freqRamp: 0.0,
		freqDeltaRamp: 0,
	},
];

export function get_instrument(index: number, isDrums: boolean) {
	return isDrums ? percussion_map[index - 35] : instrument_map[index];
}
